/**
 * 학교 메타 레지스트리.
 *
 * 북극성: 전국 초·중·고로 확장. 새 학교 추가는 SCHOOLS 객체에 한 항목 등록으로 끝나야 한다.
 *
 * Stage 3 에서 사진 미러를 켜면 'scrape' 가 있는 학교만 미러 대상이 된다.
 * NEIS 만 지원하는 학교(다른 시도 교육청 도메인 등)는 'scrape' 생략 가능 — 메뉴는 보이고
 * 사진은 안 보인다.
 */

import type { SchoolScrape } from './schoolScraper';

export type SchoolLevel = 'elementary' | 'middle' | 'high';

export interface SchoolConfig {
  /** URL 친화 키. /?schoolId=chonggye, /api/og?schoolId=chonggye 등에 쓰임. */
  id: string;
  /** 사용자 노출 이름. */
  name: string;
  level: SchoolLevel;
  /** 사용자 노출용 짧은 지역 표기. */
  region: string;
  /** NEIS Open API 식별자. */
  neis: { atptCode: string; schoolCode: string };
  /**
   * 학교 홈페이지 사진 스크래퍼 설정.
   * `kind` 로 도메인 분기 (`'goeay'` 경기 / `'sen-es'` 서울).
   * 생략 시 메뉴는 보이고 사진은 안 보임 (NEIS only).
   */
  scrape?: SchoolScrape;
}

// 과천시 6개 초등학교. NEIS 코드와 scrape host 는 NEIS Open API 의
// HMPG_ADRES 응답에서 직접 추출 (추정 아님). ATPT 모두 J10(경기도교육청).
//
// `mi`(메뉴 식별자) 는 청계초 = 9904 가 검증된 값. 다른 학교의 mi 는 우선 9904
// 로 두고, cron 응답의 photos.count 가 0 인 학교는 학교별로 점검 후 보정.
// 사진이 안 잡히는 학교는 잠정적으로 scrape 만 빼면 메뉴는 보이고 사진은 안
// 보이는 상태로 유지(기존 피처 플래그가 그 케이스 처리).
export const SCHOOLS: Record<string, SchoolConfig> = {
  gwacheon: {
    id: 'gwacheon',
    name: '과천초등학교',
    level: 'elementary',
    region: '경기 과천',
    neis: { atptCode: 'J10', schoolCode: '7569010' },
    scrape: { kind: 'goeay', host: 'gwacheon-e.goeay.kr', sysId: 'gwacheon-e', mi: '4417' },
  },
  kwanmun: {
    id: 'kwanmun',
    name: '관문초등학교',
    level: 'elementary',
    region: '경기 과천',
    neis: { atptCode: 'J10', schoolCode: '7569011' },
    scrape: { kind: 'goeay', host: 'kwanmun-e.goeay.kr', sysId: 'kwanmun-e', mi: '1690' },
  },
  munwon: {
    id: 'munwon',
    name: '문원초등학교',
    level: 'elementary',
    region: '경기 과천',
    neis: { atptCode: 'J10', schoolCode: '7569018' },
    scrape: { kind: 'goeay', host: 'munwon-e.goeay.kr', sysId: 'munwon-e', mi: '6562' },
  },
  chonggye: {
    id: 'chonggye',
    name: '청계초등학교',
    level: 'elementary',
    region: '경기 과천',
    neis: { atptCode: 'J10', schoolCode: '7569109' },
    scrape: { kind: 'goeay', host: 'chonggye-e.goeay.kr', sysId: 'chonggye-e', mi: '9904' },
  },
  gcgh: {
    id: 'gcgh',
    name: '과천갈현초등학교',
    level: 'elementary',
    region: '경기 과천',
    neis: { atptCode: 'J10', schoolCode: '7569213' },
    scrape: { kind: 'goeay', host: 'gcgh-e.goeay.kr', sysId: 'gcgh-e', mi: '4317' },
  },
  yulmok: {
    id: 'yulmok',
    name: '과천율목초등학교',
    level: 'elementary',
    region: '경기 과천',
    neis: { atptCode: 'J10', schoolCode: '7569216' },
    scrape: { kind: 'goeay', host: 'yulmok-e.goeay.kr', sysId: 'yulmok-e', mi: '10984' },
  },

  // 의왕시 15개교 — scripts/build-school-config.mjs 자동 추출
  galmoe: {
    id: 'galmoe',
    name: '갈뫼초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642003' },
    scrape: { kind: 'goeay', host: 'galmoecho.goegu.kr', sysId: 'galmoecho', mi: '1287' },
  },
  gocheon: {
    id: 'gocheon',
    name: '고천초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642004' },
    scrape: { kind: 'goeay', host: 'gocheoncho.goegu.kr', sysId: 'gocheoncho', mi: '1435' },
  },
  naedong: {
    id: 'naedong',
    name: '내동초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642076' },
    scrape: { kind: 'goeay', host: 'naedongcho.goegu.kr', sysId: 'naedongcho', mi: '3738' },
  },
  naeson: {
    id: 'naeson',
    name: '내손초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642014' },
    scrape: { kind: 'goeay', host: 'naesoncho.goegu.kr', sysId: 'naesoncho', mi: '4194' },
  },
  deokjang: {
    id: 'deokjang',
    name: '덕장초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642016' },
    scrape: { kind: 'goeay', host: 'deokjangcho.goegu.kr', sysId: 'deokjangcho', mi: '6782' },
  },
  morak: {
    id: 'morak',
    name: '모락초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642077' },
    scrape: { kind: 'goeay', host: 'morakcho.goegu.kr', sysId: 'morakcho', mi: '5491' },
  },
  baekwoon: {
    id: 'baekwoon',
    name: '백운초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642020' },
    scrape: { kind: 'goeay', host: 'baekwooncho.goegu.kr', sysId: 'baekwooncho', mi: '2348' },
  },
  baekunhosu: {
    id: 'baekunhosu',
    name: '백운호수초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642141' },
    scrape: { kind: 'goeay', host: 'baekunhosucho.goegu.kr', sysId: 'baekunhosucho', mi: '6442' },
  },
  ojeon: {
    id: 'ojeon',
    name: '오전초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642025' },
    scrape: { kind: 'goeay', host: 'ojeoncho.goegu.kr', sysId: 'ojeoncho', mi: '4851' },
  },
  wanggok: {
    id: 'wanggok',
    name: '왕곡초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642026' },
    scrape: { kind: 'goeay', host: 'wanggokcho.goegu.kr', sysId: 'wanggokcho', mi: '5675' },
  },
  uiwangdeokseong: {
    id: 'uiwangdeokseong',
    name: '의왕덕성초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642028' },
    scrape: { kind: 'goeay', host: 'uiwangdeokseongcho.goegu.kr', sysId: 'uiwangdeokseongcho', mi: '2771' },
  },
  uiwangbugok: {
    id: 'uiwangbugok',
    name: '의왕부곡초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642029' },
    scrape: { kind: 'goeay', host: 'uiwangbugokcho.goegu.kr', sysId: 'uiwangbugokcho', mi: '3003' },
  },
  uiwang: {
    id: 'uiwang',
    name: '의왕초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642030' },
    scrape: { kind: 'goeay', host: 'uiwangcho.goegu.kr', sysId: 'uiwangcho', mi: '3485' },
  },
  uiwangpureun: {
    id: 'uiwangpureun',
    name: '의왕푸른초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642152' },
    scrape: { kind: 'goeay', host: 'uiwangpureuncho.goegu.kr', sysId: 'uiwangpureuncho', mi: '7471' },
  },
  poil: {
    id: 'poil',
    name: '포일초등학교',
    level: 'elementary',
    region: '경기 의왕',
    neis: { atptCode: 'J10', schoolCode: '7642126' },
    scrape: { kind: 'goeay', host: 'poilcho.goegu.kr', sysId: 'poilcho', mi: '5084' },
  },

  // 안양시 41개교 — scripts/build-school-config.mjs 자동 추출
  // (동안구 26 + 만안구 15. 모두 *-e.goeay.kr 패턴)
  kwanyang: {
    id: 'kwanyang',
    name: '관양초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569012' },
    scrape: { kind: 'goeay', host: 'kwanyang-e.goeay.kr', sysId: 'kwanyang-e', mi: '1753' },
  },
  kwiin: {
    id: 'kwiin',
    name: '귀인초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569013' },
    scrape: { kind: 'goeay', host: 'kwiin-e.goeay.kr', sysId: 'kwiin-e', mi: '6187' },
  },
  nanum: {
    id: 'nanum',
    name: '나눔초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569014' },
    scrape: { kind: 'goeay', host: 'nanum-e.goeay.kr', sysId: 'nanum-e', mi: '1848' },
  },
  daran: {
    id: 'daran',
    name: '달안초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569015' },
    scrape: { kind: 'goeay', host: 'daran-e.goeay.kr', sysId: 'daran-e', mi: '6258' },
  },
  dongan: {
    id: 'dongan',
    name: '동안초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569017' },
    scrape: { kind: 'goeay', host: 'dongan-e.goeay.kr', sysId: 'dongan-e', mi: '6342' },
  },
  minbaeg: {
    id: 'minbaeg',
    name: '민백초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569021' },
    scrape: { kind: 'goeay', host: 'minbaeg-e.goeay.kr', sysId: 'minbaeg-e', mi: '2479' },
  },
  beolmal: {
    id: 'beolmal',
    name: '벌말초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569023' },
    scrape: { kind: 'goeay', host: 'beolmal-e.goeay.kr', sysId: 'beolmal-e', mi: '3838' },
  },
  bumgye: {
    id: 'bumgye',
    name: '범계초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569024' },
    scrape: { kind: 'goeay', host: 'bumgye-e.goeay.kr', sysId: 'bumgye-e', mi: '3632' },
  },
  burim: {
    id: 'burim',
    name: '부림초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569025' },
    scrape: { kind: 'goeay', host: 'burim-e.goeay.kr', sysId: 'burim-e', mi: '3066' },
  },
  bisan: {
    id: 'bisan',
    name: '비산초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569026' },
    scrape: { kind: 'goeay', host: 'bisan-e.goeay.kr', sysId: 'bisan-e', mi: '3851' },
  },
  sammoru: {
    id: 'sammoru',
    name: '샘모루초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569029' },
    scrape: { kind: 'goeay', host: 'sammoru-e.goeay.kr', sysId: 'sammoru-e', mi: '6894' },
  },
  kwanak: {
    id: 'kwanak',
    name: '안양관악초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569033' },
    scrape: { kind: 'goeay', host: 'kwanak-e.goeay.kr', sysId: 'kwanak-e', mi: '7058' },
  },
  aynam: {
    id: 'aynam',
    name: '안양남초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569034' },
    scrape: { kind: 'goeay', host: 'aynam-e.goeay.kr', sysId: 'aynam-e', mi: '2737' },
  },
  aydh: {
    id: 'aydh',
    name: '안양덕현초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569035' },
    scrape: { kind: 'goeay', host: 'aydh-e.goeay.kr', sysId: 'aydh-e', mi: '7132' },
  },
  anyangdong: {
    id: 'anyangdong',
    name: '안양동초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569036' },
    scrape: { kind: 'goeay', host: 'anyangdong-e.goeay.kr', sysId: 'anyangdong-e', mi: '4637' },
  },
  aybuan: {
    id: 'aybuan',
    name: '안양부안초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569037' },
    scrape: { kind: 'goeay', host: 'aybuan-e.goeay.kr', sysId: 'aybuan-e', mi: '1941' },
  },
  buheung: {
    id: 'buheung',
    name: '안양부흥초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569038' },
    scrape: { kind: 'goeay', host: 'buheung-e.goeay.kr', sysId: 'buheung-e', mi: '2336' },
  },
  ayshingi: {
    id: 'ayshingi',
    name: '안양신기초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569040' },
    scrape: { kind: 'goeay', host: 'ayshingi-e.goeay.kr', sysId: 'ayshingi-e', mi: '2056' },
  },
  ayja: {
    id: 'ayja',
    name: '안양중앙초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569042' },
    scrape: { kind: 'goeay', host: 'ayja-e.goeay.kr', sysId: 'ayja-e', mi: '7373' },
  },
  indeogwon: {
    id: 'indeogwon',
    name: '인덕원초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569046' },
    scrape: { kind: 'goeay', host: 'indeogwon-e.goeay.kr', sysId: 'indeogwon-e', mi: '7495' },
  },
  pc: {
    id: 'pc',
    name: '평촌초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569047' },
    scrape: { kind: 'goeay', host: 'pc-e.goeay.kr', sysId: 'pc-e', mi: '7709' },
  },
  haeoleum: {
    id: 'haeoleum',
    name: '해오름초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569175' },
    scrape: { kind: 'goeay', host: 'haeoleum-e.goeay.kr', sysId: 'haeoleum-e', mi: '3522' },
  },
  ayhogye: {
    id: 'ayhogye',
    name: '호계초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569048' },
    scrape: { kind: 'goeay', host: 'ayhogye-e.goeay.kr', sysId: 'ayhogye-e', mi: '3975' },
  },
  hoseong: {
    id: 'hoseong',
    name: '호성초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569049' },
    scrape: { kind: 'goeay', host: 'hoseong-e.goeay.kr', sysId: 'hoseong-e', mi: '7806' },
  },
  howon: {
    id: 'howon',
    name: '호원초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569050' },
    scrape: { kind: 'goeay', host: 'howon-e.goeay.kr', sysId: 'howon-e', mi: '7863' },
  },
  heesung: {
    id: 'heesung',
    name: '희성초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569052' },
    scrape: { kind: 'goeay', host: 'heesung-e.goeay.kr', sysId: 'heesung-e', mi: '3004' },
  },
  dukchon: {
    id: 'dukchon',
    name: '덕천초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569016' },
    scrape: { kind: 'goeay', host: 'dukchon-e.goeay.kr', sysId: 'dukchon-e', mi: '4827' },
  },
  manan: {
    id: 'manan',
    name: '만안초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569019' },
    scrape: { kind: 'goeay', host: 'manan-e.goeay.kr', sysId: 'manan-e', mi: '10584' },
  },
  myeonghak: {
    id: 'myeonghak',
    name: '명학초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569020' },
    scrape: { kind: 'goeay', host: 'myeonghak-e.goeay.kr', sysId: 'myeonghak-e', mi: '6493' },
  },
  bakdal: {
    id: 'bakdal',
    name: '박달초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569022' },
    scrape: { kind: 'goeay', host: 'bakdal-e.goeay.kr', sysId: 'bakdal-e', mi: '3355' },
  },
  sambong: {
    id: 'sambong',
    name: '삼봉초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569027' },
    scrape: { kind: 'goeay', host: 'sambong-e.goeay.kr', sysId: 'sambong-e', mi: '9678' },
  },
  samsung: {
    id: 'samsung',
    name: '삼성초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569028' },
    scrape: { kind: 'goeay', host: 'samsung-e.goeay.kr', sysId: 'samsung-e', mi: '6769' },
  },
  suksu: {
    id: 'suksu',
    name: '석수초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569030' },
    scrape: { kind: 'goeay', host: 'suksu-e.goeay.kr', sysId: 'suksu-e', mi: '7001' },
  },
  sinan: {
    id: 'sinan',
    name: '신안초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569031' },
    scrape: { kind: 'goeay', host: 'sinan-e.goeay.kr', sysId: 'sinan-e', mi: '2212' },
  },
  ayseo: {
    id: 'ayseo',
    name: '안양서초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569039' },
    scrape: { kind: 'goeay', host: 'ayseo-e.goeay.kr', sysId: 'ayseo-e', mi: '7235' },
  },
  ayangji: {
    id: 'ayangji',
    name: '안양양지초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569041' },
    scrape: { kind: 'goeay', host: 'ayangji-e.goeay.kr', sysId: 'ayangji-e', mi: '2324' },
  },
  anyang: {
    id: 'anyang',
    name: '안양초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569032' },
    scrape: { kind: 'goeay', host: 'anyang-e.goeay.kr', sysId: 'anyang-e', mi: '4500' },
  },
  ayhoam: {
    id: 'ayhoam',
    name: '안양호암초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569043' },
    scrape: { kind: 'goeay', host: 'ayhoam-e.goeay.kr', sysId: 'ayhoam-e', mi: '4658' },
  },
  anil: {
    id: 'anil',
    name: '안일초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569044' },
    scrape: { kind: 'goeay', host: 'anil-e.goeay.kr', sysId: 'anil-e', mi: '1867' },
  },
  yeonhyeon: {
    id: 'yeonhyeon',
    name: '연현초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569045' },
    scrape: { kind: 'goeay', host: 'yeonhyeon-e.goeay.kr', sysId: 'yeonhyeon-e', mi: '3010' },
  },
  hwachang: {
    id: 'hwachang',
    name: '화창초등학교',
    level: 'elementary',
    region: '경기 안양',
    neis: { atptCode: 'J10', schoolCode: '7569051' },
    scrape: { kind: 'goeay', host: 'hwachang-e.goeay.kr', sysId: 'hwachang-e', mi: '5338' },
  },

  // 경기 군포 — 군포의왕 통합 교육청 (의왕 측은 위 의왕 그룹 참고).
  gunpo: {
    id: 'gunpo',
    name: '군포초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642010' },
    scrape: { kind: 'goeay', host: 'gunpocho.goegu.kr', sysId: 'gunpocho', mi: '2365' },
  },
  geumjeong: {
    id: 'geumjeong',
    name: '금정초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642013' },
    scrape: { kind: 'goeay', host: 'geumjeongcho.goegu.kr', sysId: 'geumjeongcho', mi: '5307' },
  },
  sanbon: {
    id: 'sanbon',
    name: '산본초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642021' },
    scrape: { kind: 'goeay', host: 'sanboncho.goegu.kr', sysId: 'sanboncho', mi: '6205' },
  },
  gunpoyangjeong: {
    id: 'gunpoyangjeong',
    name: '군포양정초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642008' },
    scrape: { kind: 'goeay', host: 'gunpoyangjeongcho.goegu.kr', sysId: 'gunpoyangjeongcho', mi: '1783' },
  },
  heungjin: {
    id: 'heungjin',
    name: '흥진초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642032' },
    scrape: { kind: 'goeay', host: 'heungjincho.goegu.kr', sysId: 'heungjincho', mi: '4916' },
  },
  gwangjeong: {
    id: 'gwangjeong',
    name: '광정초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642007' },
    scrape: { kind: 'goeay', host: 'gwangjeongcho.goegu.kr', sysId: 'gwangjeongcho', mi: '1619' },
  },
  neungnae: {
    id: 'neungnae',
    name: '능내초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642015' },
    scrape: { kind: 'goeay', host: 'neungnaecho.goegu.kr', sysId: 'neungnaecho', mi: '4995' },
  },
  gungnae: {
    id: 'gungnae',
    name: '궁내초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642012' },
    scrape: { kind: 'goeay', host: 'gungnaecho.goegu.kr', sysId: 'gungnaecho', mi: '4343' },
  },
  taeeul: {
    id: 'taeeul',
    name: '태을초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642031' },
    scrape: { kind: 'goeay', host: 'taeeulcho.goegu.kr', sysId: 'taeeulcho', mi: '4138' },
  },
  ogeum: {
    id: 'ogeum',
    name: '오금초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642024' },
    scrape: { kind: 'goeay', host: 'ogeumcho.goegu.kr', sysId: 'ogeumcho', mi: '3982' },
  },
  songan: {
    id: 'songan',
    name: '송안초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642143' },
    scrape: { kind: 'goeay', host: 'songancho.goegu.kr', sysId: 'songancho', mi: '6692' },
  },
  gunpodaeya: {
    id: 'gunpodaeya',
    name: '군포대야초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642075' },
    scrape: { kind: 'goeay', host: 'gunpodaeyacho.goegu.kr', sysId: 'gunpodaeyacho', mi: '6864' },
  },
  haneol: {
    id: 'haneol',
    name: '한얼초등학교',
    level: 'elementary',
    region: '경기 군포',
    neis: { atptCode: 'J10', schoolCode: '7642122' },
    scrape: { kind: 'goeay', host: 'haneolcho.goegu.kr', sysId: 'haneolcho', mi: '5847' },
  },

  // 서울 서초구 — 첫 다른 시도(B10) 확장 (Stage 14, 2026-04-27 + Stage 14-1 사진, 2026-05-02).
  // 23교 sen.es.kr — Stage 14-1 에서 seoulSchoolScraper 신규 + scrape 부여.
  // 1교 사립 (seoul_gyeseong, gyeseong1882.es.kr) — sen.es.kr 패턴 아님 → 메뉴만, scrape 보류.
  // host 는 NEIS HMPG_ADRES 일괄 추출값 그대로 (id 와 subdomain 이 다른 학교 다수: banpo→seoulbanpo, seowon→seo-won, seoil→seoulseoil).
  // id 는 모두 `seoul_` prefix — 다른 시도 학교와 명확히 구분 + 충돌 회피.
  seoul_gyeseong: {
    id: 'seoul_gyeseong',
    name: '계성초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091368' },
    // 사립 — gyeseong1882.es.kr 의 PHP 게시판형 식단표 (Stage 14-1-2, 2026-05-02).
    // 다른 사립 추가 시 sajipSchoolScraper.ts 그대로 재사용 가능.
    scrape: {
      kind: 'sajip-bbs',
      host: 'www.gyeseong1882.es.kr',
      bbsCategory: 'special_food_plan',
    },
  },
  seoul_snueps: {
    id: 'seoul_snueps',
    name: '서울교육대학교부설초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091367' },
    scrape: { kind: 'sen-es', host: 'snueps.sen.es.kr' },
  },
  seoul_maeheon: {
    id: 'seoul_maeheon',
    name: '서울매헌초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091384' },
    scrape: { kind: 'sen-es', host: 'maeheon.sen.es.kr' },
  },
  seoul_banwon: {
    id: 'seoul_banwon',
    name: '서울반원초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091385' },
    scrape: { kind: 'sen-es', host: 'banwon.sen.es.kr' },
  },
  seoul_banpo: {
    id: 'seoul_banpo',
    name: '서울반포초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091386' },
    scrape: { kind: 'sen-es', host: 'seoulbanpo.sen.es.kr' },
  },
  seoul_bangbae: {
    id: 'seoul_bangbae',
    name: '서울방배초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091387' },
    scrape: { kind: 'sen-es', host: 'bangbae.sen.es.kr' },
  },
  seoul_bangil: {
    id: 'seoul_bangil',
    name: '서울방일초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091388' },
    scrape: { kind: 'sen-es', host: 'bangil.sen.es.kr' },
  },
  seoul_banghyun: {
    id: 'seoul_banghyun',
    name: '서울방현초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091389' },
    scrape: { kind: 'sen-es', host: 'banghyun.sen.es.kr' },
  },
  seoul_seorae: {
    id: 'seoul_seorae',
    name: '서울서래초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091392' },
    scrape: { kind: 'sen-es', host: 'seorae.sen.es.kr' },
  },
  seoul_seowon: {
    id: 'seoul_seowon',
    name: '서울서원초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091393' },
    scrape: { kind: 'sen-es', host: 'seo-won.sen.es.kr' },
  },
  seoul_seoi: {
    id: 'seoul_seoi',
    name: '서울서이초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091394' },
    scrape: { kind: 'sen-es', host: 'seoi.sen.es.kr' },
  },
  seoul_seoil: {
    id: 'seoul_seoil',
    name: '서울서일초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091395' },
    scrape: { kind: 'sen-es', host: 'seoulseoil.sen.es.kr' },
  },
  seoul_seocho: {
    id: 'seoul_seocho',
    name: '서울서초초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091396' },
    scrape: { kind: 'sen-es', host: 'seocho.sen.es.kr' },
  },
  seoul_sindong: {
    id: 'seoul_sindong',
    name: '서울신동초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091399' },
    scrape: { kind: 'sen-es', host: 'sindong.sen.es.kr' },
  },
  seoul_sinjung: {
    id: 'seoul_sinjung',
    name: '서울신중초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091400' },
    scrape: { kind: 'sen-es', host: 'sinjung.sen.es.kr' },
  },
  seoul_yangjae: {
    id: 'seoul_yangjae',
    name: '서울양재초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091402' },
    scrape: { kind: 'sen-es', host: 'yangjae.sen.es.kr' },
  },
  seoul_eonnam: {
    id: 'seoul_eonnam',
    name: '서울언남초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091404' },
    scrape: { kind: 'sen-es', host: 'eonnam.sen.es.kr' },
  },
  seoul_woomyeon: {
    id: 'seoul_woomyeon',
    name: '서울우면초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091419' },
    scrape: { kind: 'sen-es', host: 'woomyeon.sen.es.kr' },
  },
  seoul_woosol: {
    id: 'seoul_woosol',
    name: '서울우솔초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091460' },
    scrape: { kind: 'sen-es', host: 'woosol.sen.es.kr' },
  },
  seoul_wooam: {
    id: 'seoul_wooam',
    name: '서울우암초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091410' },
    scrape: { kind: 'sen-es', host: 'wooam.sen.es.kr' },
  },
  seoul_wonmyong: {
    id: 'seoul_wonmyong',
    name: '서울원명초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091411' },
    scrape: { kind: 'sen-es', host: 'wonmyong.sen.es.kr' },
  },
  seoul_wonchon: {
    id: 'seoul_wonchon',
    name: '서울원촌초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091412' },
    scrape: { kind: 'sen-es', host: 'wonchon.sen.es.kr' },
  },
  seoul_isu: {
    id: 'seoul_isu',
    name: '서울이수초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091413' },
    scrape: { kind: 'sen-es', host: 'isu.sen.es.kr' },
  },
  seoul_jamwon: {
    id: 'seoul_jamwon',
    name: '서울잠원초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091415' },
    scrape: { kind: 'sen-es', host: 'jamwon.sen.es.kr' },
  },
};

export const DEFAULT_SCHOOL_ID = 'chonggye';

/**
 * id 로 학교 조회. 잘못된 id 는 기본 학교(청계초)로 폴백.
 * 의도적으로 throw 하지 않는다 — 잘못된 schoolId 가 넘어와도 서비스는 동작해야 한다.
 */
export function getSchool(id?: string | null): SchoolConfig {
  if (id && SCHOOLS[id]) return SCHOOLS[id];
  return SCHOOLS[DEFAULT_SCHOOL_ID];
}

/** 등록된 모든 학교. cron 등에서 순회 용도. */
export function listSchools(): SchoolConfig[] {
  return Object.values(SCHOOLS);
}
