/**
 * 서울 도봉구 23교 — Stage 14-13 (2026-05-02), Phase B 여섯 번째 자치구.
 *
 * 모두 sen.es.kr. 서울 prefix 없는 사립 2교 (동북·한신) 도 host sen.es.kr.
 */

import type { SchoolConfig } from '../index';

export const DOBONG_SCHOOLS: Record<string, SchoolConfig> = {
  dongbuk: {
    id: 'dongbuk',
    name: '동북초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051109' },
    scrape: { kind: 'sen-es', host: 'dongbuk.sen.es.kr' },
  },
  seoul_gain: {
    id: 'seoul_gain',
    name: '서울가인초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051111' },
    scrape: { kind: 'sen-es', host: 'seoulgain.sen.es.kr' },
  },
  seoul_nuwon: {
    id: 'seoul_nuwon',
    name: '서울누원초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051118' },
    scrape: { kind: 'sen-es', host: 'nuwon.sen.es.kr' },
  },
  seoul_dobong: {
    id: 'seoul_dobong',
    name: '서울도봉초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051121' },
    scrape: { kind: 'sen-es', host: 'dobong.sen.es.kr' },
  },
  seoul_banghak: {
    id: 'seoul_banghak',
    name: '서울방학초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051123' },
    scrape: { kind: 'sen-es', host: 'banghakcho.sen.es.kr' },
  },
  seoul_baegun: {
    id: 'seoul_baegun',
    name: '서울백운초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051124' },
    scrape: { kind: 'sen-es', host: 's-baegun.sen.es.kr' },
  },
  seoul_sungmi: {
    id: 'seoul_sungmi',
    name: '서울숭미초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051136' },
    scrape: { kind: 'sen-es', host: 'sungmi.sen.es.kr' },
  },
  seoul_sinbanghak: {
    id: 'seoul_sinbanghak',
    name: '서울신방학초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051138' },
    scrape: { kind: 'sen-es', host: 'sbh.sen.es.kr' },
  },
  seoul_shinchang: {
    id: 'seoul_shinchang',
    name: '서울신창초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051140' },
    scrape: { kind: 'sen-es', host: 'shinchang.sen.es.kr' },
  },
  seoul_sinhak: {
    id: 'seoul_sinhak',
    name: '서울신학초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051141' },
    scrape: { kind: 'sen-es', host: 'seoulsinhak.sen.es.kr' },
  },
  seoul_sinhwa: {
    id: 'seoul_sinhwa',
    name: '서울신화초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051142' },
    scrape: { kind: 'sen-es', host: 'sinhwa.sen.es.kr' },
  },
  seoul_ssangmun: {
    id: 'seoul_ssangmun',
    name: '서울쌍문초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051143' },
    scrape: { kind: 'sen-es', host: 'ssangmun.sen.es.kr' },
  },
  seoul_obong: {
    id: 'seoul_obong',
    name: '서울오봉초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051146' },
    scrape: { kind: 'sen-es', host: 'obong.sen.es.kr' },
  },
  seoul_wolcheon: {
    id: 'seoul_wolcheon',
    name: '서울월천초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051152' },
    scrape: { kind: 'sen-es', host: 'wol.sen.es.kr' },
  },
  seoul_jawoon: {
    id: 'seoul_jawoon',
    name: '서울자운초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051154' },
    scrape: { kind: 'sen-es', host: 'jawoon.sen.es.kr' },
  },
  seoul_changkyung: {
    id: 'seoul_changkyung',
    name: '서울창경초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051159' },
    scrape: { kind: 'sen-es', host: 'changkyung.sen.es.kr' },
  },
  seoul_changdo: {
    id: 'seoul_changdo',
    name: '서울창도초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051160' },
    scrape: { kind: 'sen-es', host: 'changdo.sen.es.kr' },
  },
  seoul_changdong: {
    id: 'seoul_changdong',
    name: '서울창동초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051161' },
    scrape: { kind: 'sen-es', host: 'changdong-s.sen.es.kr' },
  },
  seoul_changlim: {
    id: 'seoul_changlim',
    name: '서울창림초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051162' },
    scrape: { kind: 'sen-es', host: 'changlim.sen.es.kr' },
  },
  seoul_changwon: {
    id: 'seoul_changwon',
    name: '서울창원초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051163' },
    scrape: { kind: 'sen-es', host: 'changwon.sen.es.kr' },
  },
  seoul_changil: {
    id: 'seoul_changil',
    name: '서울창일초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051164' },
    scrape: { kind: 'sen-es', host: 'changil.sen.es.kr' },
  },
  seoul_chodang: {
    id: 'seoul_chodang',
    name: '서울초당초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051166' },
    scrape: { kind: 'sen-es', host: 'chodang.sen.es.kr' },
  },
  hansin: {
    id: 'hansin',
    name: '한신초등학교',
    level: 'elementary',
    region: '서울 도봉',
    neis: { atptCode: 'B10', schoolCode: '7051172' },
    scrape: { kind: 'sen-es', host: 'ihansin.sen.es.kr' },
  },
};
