/**
 * 서울 동대문구 21교 — Stage 14-22 (2026-05-03), Phase E 첫 자치구.
 *
 * 모두 sen.es.kr (사립 경희·은석 포함). id 충돌 없음.
 * 삼육초 → seoul36.sen.es.kr (특이 host).
 */

import type { SchoolConfig } from '../index';

export const DONGDAEMUN_SCHOOLS: Record<string, SchoolConfig> = {
  kyunghee_es: {
    id: 'kyunghee_es',
    name: '경희초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021079' },
    scrape: { kind: 'sen-es', host: 'kyunghee.sen.es.kr' },
  },
  seoul_kunja: {
    id: 'seoul_kunja',
    name: '서울군자초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021082' },
    scrape: { kind: 'sen-es', host: 'kunja.sen.es.kr' },
  },
  seoul_dapsimni: {
    id: 'seoul_dapsimni',
    name: '서울답십리초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021083' },
    scrape: { kind: 'sen-es', host: 'dapsimni.sen.es.kr' },
  },
  seoul_dongdab: {
    id: 'seoul_dongdab',
    name: '서울동답초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021084' },
    scrape: { kind: 'sen-es', host: 'dongdab.sen.es.kr' },
  },
  seoul_baebong: {
    id: 'seoul_baebong',
    name: '서울배봉초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021095' },
    scrape: { kind: 'sen-es', host: 'baebong.sen.es.kr' },
  },
  seoul_seoul36: {
    id: 'seoul_seoul36',
    name: '서울삼육초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021168' },
    scrape: { kind: 'sen-es', host: 'seoul36.sen.es.kr' },
  },
  seoul_shindap: {
    id: 'seoul_shindap',
    name: '서울신답초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021099' },
    scrape: { kind: 'sen-es', host: 'shindap.sen.es.kr' },
  },
  seoul_anpyeong: {
    id: 'seoul_anpyeong',
    name: '서울안평초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021102' },
    scrape: { kind: 'sen-es', host: 'anpyeong.sen.es.kr' },
  },
  seoul_yongdu: {
    id: 'seoul_yongdu',
    name: '서울용두초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021103' },
    scrape: { kind: 'sen-es', host: 'yongdu.sen.es.kr' },
  },
  seoul_imun: {
    id: 'seoul_imun',
    name: '서울이문초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021105' },
    scrape: { kind: 'sen-es', host: 'imun.sen.es.kr' },
  },
  seoul_jangpyung: {
    id: 'seoul_jangpyung',
    name: '서울장평초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021106' },
    scrape: { kind: 'sen-es', host: 'jang-pyung.sen.es.kr' },
  },
  seoul_jeongok: {
    id: 'seoul_jeongok',
    name: '서울전곡초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021107' },
    scrape: { kind: 'sen-es', host: 'jeongok.sen.es.kr' },
  },
  seoul_jeonnong: {
    id: 'seoul_jeonnong',
    name: '서울전농초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021108' },
    scrape: { kind: 'sen-es', host: 'jeonnong.sen.es.kr' },
  },
  seoul_jeondong: {
    id: 'seoul_jeondong',
    name: '서울전동초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021109' },
    scrape: { kind: 'sen-es', host: 'jeondong.sen.es.kr' },
  },
  seoul_jongam: {
    id: 'seoul_jongam',
    name: '서울종암초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021110' },
    scrape: { kind: 'sen-es', host: 'jongam.sen.es.kr' },
  },
  seoul_chongryang: {
    id: 'seoul_chongryang',
    name: '서울청량초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021116' },
    scrape: { kind: 'sen-es', host: 'chongryang.sen.es.kr' },
  },
  seoul_hongneung: {
    id: 'seoul_hongneung',
    name: '서울홍릉초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021117' },
    scrape: { kind: 'sen-es', host: 'hongneung.sen.es.kr' },
  },
  seoul_hongpa: {
    id: 'seoul_hongpa',
    name: '서울홍파초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021118' },
    scrape: { kind: 'sen-es', host: 'hongpa.sen.es.kr' },
  },
  seoul_hwykyung: {
    id: 'seoul_hwykyung',
    name: '서울휘경초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021119' },
    scrape: { kind: 'sen-es', host: 'hwykyung.sen.es.kr' },
  },
  seoul_hwibong: {
    id: 'seoul_hwibong',
    name: '서울휘봉초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021120' },
    scrape: { kind: 'sen-es', host: 'hwibong.sen.es.kr' },
  },
  eunseok: {
    id: 'eunseok',
    name: '은석초등학교',
    level: 'elementary',
    region: '서울 동대문',
    neis: { atptCode: 'B10', schoolCode: '7021121' },
    scrape: { kind: 'sen-es', host: 'eunseok.sen.es.kr' },
  },
};
