/**
 * 서울 동작구 21교 — Stage 14-2 (2026-05-02), Phase A 첫 자치구.
 *
 * 모두 sen.es.kr 패턴. 중앙대 부속 (cau.sen.es.kr) 도 같은 sen-es scraper 동작.
 * id 충돌 회피 위해 모두 `seoul_` prefix.
 * NEIS HMPG_ADRES 일괄 추출값 그대로 (id 와 subdomain 다른 케이스 다수 —
 * sangdo→seoulsangdo, sanghyun→ssh, shinnamsung·shinsangdo 등).
 */

import type { SchoolConfig } from '../index';

export const DONGJAK_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_gangnam: {
    id: 'seoul_gangnam',
    name: '서울강남초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132080' },
    scrape: { kind: 'sen-es', host: 'gangnam.sen.es.kr' },
  },
  seoul_namsa: {
    id: 'seoul_namsa',
    name: '서울남사초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132087' },
    scrape: { kind: 'sen-es', host: 'namsa.sen.es.kr' },
  },
  seoul_namsung: {
    id: 'seoul_namsung',
    name: '서울남성초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132088' },
    scrape: { kind: 'sen-es', host: 'namsung.sen.es.kr' },
  },
  seoul_noryangjin: {
    id: 'seoul_noryangjin',
    name: '서울노량진초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132089' },
    scrape: { kind: 'sen-es', host: 'noryangjin.sen.es.kr' },
  },
  seoul_daelim: {
    id: 'seoul_daelim',
    name: '서울대림초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132091' },
    scrape: { kind: 'sen-es', host: 'seouldaelim.sen.es.kr' },
  },
  seoul_dongjak: {
    id: 'seoul_dongjak',
    name: '서울동작초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132092' },
    scrape: { kind: 'sen-es', host: 'dongjak.sen.es.kr' },
  },
  seoul_munchang: {
    id: 'seoul_munchang',
    name: '서울문창초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132093' },
    scrape: { kind: 'sen-es', host: 'munchang.sen.es.kr' },
  },
  seoul_boramae: {
    id: 'seoul_boramae',
    name: '서울보라매초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132095' },
    scrape: { kind: 'sen-es', host: 'boramae.sen.es.kr' },
  },
  seoul_bondong: {
    id: 'seoul_bondong',
    name: '서울본동초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132096' },
    scrape: { kind: 'sen-es', host: 'bondong.sen.es.kr' },
  },
  seoul_samil: {
    id: 'seoul_samil',
    name: '서울삼일초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132101' },
    scrape: { kind: 'sen-es', host: 'samil.sen.es.kr' },
  },
  seoul_sangdo: {
    id: 'seoul_sangdo',
    name: '서울상도초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132102' },
    scrape: { kind: 'sen-es', host: 'seoulsangdo.sen.es.kr' },
  },
  seoul_sanghyun: {
    id: 'seoul_sanghyun',
    name: '서울상현초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132103' },
    scrape: { kind: 'sen-es', host: 'ssh.sen.es.kr' },
  },
  seoul_singil: {
    id: 'seoul_singil',
    name: '서울신길초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132104' },
    scrape: { kind: 'sen-es', host: 'singil.sen.es.kr' },
  },
  seoul_shinnamsung: {
    id: 'seoul_shinnamsung',
    name: '서울신남성초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132105' },
    scrape: { kind: 'sen-es', host: 'shinnamsung.sen.es.kr' },
  },
  seoul_shinsangdo: {
    id: 'seoul_shinsangdo',
    name: '서울신상도초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132108' },
    scrape: { kind: 'sen-es', host: 'shinsangdo.sen.es.kr' },
  },
  seoul_yeongbon: {
    id: 'seoul_yeongbon',
    name: '서울영본초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132111' },
    scrape: { kind: 'sen-es', host: 'yeongbon.sen.es.kr' },
  },
  seoul_younghwa: {
    id: 'seoul_younghwa',
    name: '서울영화초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132112' },
    scrape: { kind: 'sen-es', host: 'younghwa.sen.es.kr' },
  },
  seoul_eunlo: {
    id: 'seoul_eunlo',
    name: '서울은로초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132115' },
    scrape: { kind: 'sen-es', host: 'eunlo.sen.es.kr' },
  },
  seoul_haenglim: {
    id: 'seoul_haenglim',
    name: '서울행림초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132120' },
    scrape: { kind: 'sen-es', host: 'hrim.sen.es.kr' },
  },
  seoul_heukseok: {
    id: 'seoul_heukseok',
    name: '서울흑석초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132121' },
    scrape: { kind: 'sen-es', host: 'heukseok.sen.es.kr' },
  },
  seoul_cau: {
    id: 'seoul_cau',
    name: '중앙대학교사범대학부속초등학교',
    level: 'elementary',
    region: '서울 동작',
    neis: { atptCode: 'B10', schoolCode: '7132122' },
    scrape: { kind: 'sen-es', host: 'cau.sen.es.kr' },
  },
};
