/**
 * 서울 은평구 30교 — Stage 14-16 (2026-05-02), Phase C 마지막 자치구.
 *
 * 모두 sen.es.kr. 사립 3교 (선일·예일·충암) 도 host sen.es.kr.
 * Phase B+C 완료 = 9구 251교.
 */

import type { SchoolConfig } from '../index';

export const EUNPYEONG_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_galhyun: {
    id: 'seoul_galhyun',
    name: '서울갈현초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031112' },
    scrape: { kind: 'sen-es', host: 'galhyun.sen.es.kr' },
  },
  seoul_gusan: {
    id: 'seoul_gusan',
    name: '서울구산초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031115' },
    scrape: { kind: 'sen-es', host: 'gusan.sen.es.kr' },
  },
  seoul_guhyun: {
    id: 'seoul_guhyun',
    name: '서울구현초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031116' },
    scrape: { kind: 'sen-es', host: 'guhyun.sen.es.kr' },
  },
  seoul_nokbun: {
    id: 'seoul_nokbun',
    name: '서울녹번초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031118' },
    scrape: { kind: 'sen-es', host: 'nokbun.sen.es.kr' },
  },
  seoul_daeeun: {
    id: 'seoul_daeeun',
    name: '서울대은초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031120' },
    scrape: { kind: 'sen-es', host: 'daeeun.sen.es.kr' },
  },
  seoul_daejo: {
    id: 'seoul_daejo',
    name: '서울대조초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031121' },
    scrape: { kind: 'sen-es', host: 'daejo.sen.es.kr' },
  },
  seoul_bukhansan: {
    id: 'seoul_bukhansan',
    name: '서울북한산초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031128' },
    scrape: { kind: 'sen-es', host: 'bukhansan.sen.es.kr' },
  },
  seoul_bulgwang: {
    id: 'seoul_bulgwang',
    name: '서울불광초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031129' },
    scrape: { kind: 'sen-es', host: 'bulgwang.sen.es.kr' },
  },
  seoul_sangsin: {
    id: 'seoul_sangsin',
    name: '서울상신초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031130' },
    scrape: { kind: 'sen-es', host: 'sangsin.sen.es.kr' },
  },
  seoul_seosin: {
    id: 'seoul_seosin',
    name: '서울서신초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031135' },
    scrape: { kind: 'sen-es', host: 'susin.sen.es.kr' },
  },
  seoul_suri: {
    id: 'seoul_suri',
    name: '서울수리초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031230' },
    scrape: { kind: 'sen-es', host: 'suri.sen.es.kr' },
  },
  seoul_susaek: {
    id: 'seoul_susaek',
    name: '서울수색초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031140' },
    scrape: { kind: 'sen-es', host: 'susaek.sen.es.kr' },
  },
  seoul_sindo: {
    id: 'seoul_sindo',
    name: '서울신도초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031141' },
    scrape: { kind: 'sen-es', host: 'sindo.sen.es.kr' },
  },
  seoul_sinsa: {
    id: 'seoul_sinsa',
    name: '서울신사초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031143' },
    scrape: { kind: 'sen-es', host: 'shinsa.sen.es.kr' },
  },
  seoul_eoul: {
    id: 'seoul_eoul',
    name: '서울어울초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031285' },
    scrape: { kind: 'sen-es', host: 'urwool.sen.es.kr' },
  },
  seoul_yeokchon: {
    id: 'seoul_yeokchon',
    name: '서울역촌초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031147' },
    scrape: { kind: 'sen-es', host: 'yeokchon.sen.es.kr' },
  },
  seoul_yeonkwang: {
    id: 'seoul_yeonkwang',
    name: '서울연광초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031149' },
    scrape: { kind: 'sen-es', host: 'yeonkwang.sen.es.kr' },
  },
  seoul_yeonsin: {
    id: 'seoul_yeonsin',
    name: '서울연신초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031150' },
    scrape: { kind: 'sen-es', host: 'yeonsin.sen.es.kr' },
  },
  seoul_yeoneun: {
    id: 'seoul_yeoneun',
    name: '서울연은초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031151' },
    scrape: { kind: 'sen-es', host: 'yeoneun.sen.es.kr' },
  },
  seoul_yeoncheon: {
    id: 'seoul_yeoncheon',
    name: '서울연천초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031152' },
    scrape: { kind: 'sen-es', host: 'yc1985.sen.es.kr' },
  },
  seoul_eunmyeong: {
    id: 'seoul_eunmyeong',
    name: '서울은명초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031156' },
    scrape: { kind: 'sen-es', host: 'em.sen.es.kr' },
  },
  seoul_eunbit: {
    id: 'seoul_eunbit',
    name: '서울은빛초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031232' },
    scrape: { kind: 'sen-es', host: 'ev.sen.es.kr' },
  },
  seoul_eunjin: {
    id: 'seoul_eunjin',
    name: '서울은진초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031157' },
    scrape: { kind: 'sen-es', host: 'eunjin.sen.es.kr' },
  },
  seoul_eunpyeong: {
    id: 'seoul_eunpyeong',
    name: '서울은평초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031158' },
    scrape: { kind: 'sen-es', host: 'eunpyeong.sen.es.kr' },
  },
  seoul_eungam: {
    id: 'seoul_eungam',
    name: '서울응암초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031159' },
    scrape: { kind: 'sen-es', host: 'eungam.sen.es.kr' },
  },
  seoul_jeungsan: {
    id: 'seoul_jeungsan',
    name: '서울증산초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031162' },
    scrape: { kind: 'sen-es', host: 'jeungsancho.sen.es.kr' },
  },
  seoul_jingwan: {
    id: 'seoul_jingwan',
    name: '서울진관초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031163' },
    scrape: { kind: 'sen-es', host: 'jingwan.sen.es.kr' },
  },
  sunil: {
    id: 'sunil',
    name: '선일초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031170' },
    scrape: { kind: 'sen-es', host: 'sunil.sen.es.kr' },
  },
  yale: {
    id: 'yale',
    name: '예일초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031172' },
    scrape: { kind: 'sen-es', host: 'yale.sen.es.kr' },
  },
  choongam: {
    id: 'choongam',
    name: '충암초등학교',
    level: 'elementary',
    region: '서울 은평',
    neis: { atptCode: 'B10', schoolCode: '7031176' },
    scrape: { kind: 'sen-es', host: 'choongam.sen.es.kr' },
  },
};
