/**
 * 서울 강남구 34교 — Stage 14-4 (2026-05-02), Phase A 세 번째 자치구.
 *
 * 모두 sen.es.kr 패턴. 사립 0교. id 충돌 없음 (노트북에서 분석 완료).
 * NEIS HMPG_ADRES 일괄 추출값 그대로 (id 와 subdomain 다른 케이스 다수 —
 * seouldaegok·sdaedo·seouldaejin·seouldoseong·srng 등).
 */

import type { SchoolConfig } from '../index';

export const GANGNAM_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_gaewon: {
    id: 'seoul_gaewon',
    name: '서울개원초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091369' },
    scrape: { kind: 'sen-es', host: 'gaewon.sen.es.kr' },
  },
  seoul_gaeil: {
    id: 'seoul_gaeil',
    name: '서울개일초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091370' },
    scrape: { kind: 'sen-es', host: 'gaeil.sen.es.kr' },
  },
  seoul_gaepo: {
    id: 'seoul_gaepo',
    name: '서울개포초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091371' },
    scrape: { kind: 'sen-es', host: 'gaepo.sen.es.kr' },
  },
  seoul_gaehyeon: {
    id: 'seoul_gaehyeon',
    name: '서울개현초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091496' },
    scrape: { kind: 'sen-es', host: 'gaehyeon.sen.es.kr' },
  },
  seoul_kuryong: {
    id: 'seoul_kuryong',
    name: '서울구룡초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091372' },
    scrape: { kind: 'sen-es', host: 'kuryong.sen.es.kr' },
  },
  seoul_nonhyun: {
    id: 'seoul_nonhyun',
    name: '서울논현초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091373' },
    scrape: { kind: 'sen-es', host: 'nonhyun.sen.es.kr' },
  },
  seoul_daegok: {
    id: 'seoul_daegok',
    name: '서울대곡초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091374' },
    scrape: { kind: 'sen-es', host: 'seouldaegok.sen.es.kr' },
  },
  seoul_daedo: {
    id: 'seoul_daedo',
    name: '서울대도초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091375' },
    scrape: { kind: 'sen-es', host: 'sdaedo.sen.es.kr' },
  },
  seoul_daemo: {
    id: 'seoul_daemo',
    name: '서울대모초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091376' },
    scrape: { kind: 'sen-es', host: 'daemo.sen.es.kr' },
  },
  seoul_daewang: {
    id: 'seoul_daewang',
    name: '서울대왕초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091377' },
    scrape: { kind: 'sen-es', host: 'daewang.sen.es.kr' },
  },
  seoul_daejin: {
    id: 'seoul_daejin',
    name: '서울대진초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091378' },
    scrape: { kind: 'sen-es', host: 'seouldaejin.sen.es.kr' },
  },
  seoul_daecheong: {
    id: 'seoul_daecheong',
    name: '서울대청초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091379' },
    scrape: { kind: 'sen-es', host: 'daecheong.sen.es.kr' },
  },
  seoul_daechi: {
    id: 'seoul_daechi',
    name: '서울대치초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091380' },
    scrape: { kind: 'sen-es', host: 'daechi.sen.es.kr' },
  },
  seoul_daehyun: {
    id: 'seoul_daehyun',
    name: '서울대현초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091381' },
    scrape: { kind: 'sen-es', host: 'daehyun.sen.es.kr' },
  },
  seoul_dogok: {
    id: 'seoul_dogok',
    name: '서울도곡초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091382' },
    scrape: { kind: 'sen-es', host: 'dogok.sen.es.kr' },
  },
  seoul_doseong: {
    id: 'seoul_doseong',
    name: '서울도성초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091383' },
    scrape: { kind: 'sen-es', host: 'seouldoseong.sen.es.kr' },
  },
  seoul_bongeun: {
    id: 'seoul_bongeun',
    name: '서울봉은초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091390' },
    scrape: { kind: 'sen-es', host: 'bongeun.sen.es.kr' },
  },
  seoul_samneung: {
    id: 'seoul_samneung',
    name: '서울삼릉초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091391' },
    scrape: { kind: 'sen-es', host: 'srng.sen.es.kr' },
  },
  seoul_semyung: {
    id: 'seoul_semyung',
    name: '서울세명초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091458' },
    scrape: { kind: 'sen-es', host: 'semyung.sen.es.kr' },
  },
  seoul_suseo: {
    id: 'seoul_suseo',
    name: '서울수서초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091397' },
    scrape: { kind: 'sen-es', host: 'suseo.sen.es.kr' },
  },
  seoul_shingu: {
    id: 'seoul_shingu',
    name: '서울신구초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091398' },
    scrape: { kind: 'sen-es', host: 'shingu.sen.es.kr' },
  },
  seoul_apgujeong: {
    id: 'seoul_apgujeong',
    name: '서울압구정초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091401' },
    scrape: { kind: 'sen-es', host: 'apgujeong.sen.es.kr' },
  },
  seoul_yangjeon: {
    id: 'seoul_yangjeon',
    name: '서울양전초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091403' },
    scrape: { kind: 'sen-es', host: 'yangjeon.sen.es.kr' },
  },
  seoul_eonbuk: {
    id: 'seoul_eonbuk',
    name: '서울언북초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091405' },
    scrape: { kind: 'sen-es', host: 'eonbuk.sen.es.kr' },
  },
  seoul_eonju: {
    id: 'seoul_eonju',
    name: '서울언주초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091406' },
    scrape: { kind: 'sen-es', host: 'eonju.sen.es.kr' },
  },
  seoul_yeoksam: {
    id: 'seoul_yeoksam',
    name: '서울역삼초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091407' },
    scrape: { kind: 'sen-es', host: 'yeoksam.sen.es.kr' },
  },
  seoul_younghee: {
    id: 'seoul_younghee',
    name: '서울영희초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091408' },
    scrape: { kind: 'sen-es', host: 'younghee.sen.es.kr' },
  },
  seoul_wangbuk: {
    id: 'seoul_wangbuk',
    name: '서울왕북초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091409' },
    scrape: { kind: 'sen-es', host: 'wangbuk.sen.es.kr' },
  },
  seoul_yulhyeon: {
    id: 'seoul_yulhyeon',
    name: '서울율현초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091468' },
    scrape: { kind: 'sen-es', host: 'yulhyeon.sen.es.kr' },
  },
  seoul_ilwon: {
    id: 'seoul_ilwon',
    name: '서울일원초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091414' },
    scrape: { kind: 'sen-es', host: 'ilwon.sen.es.kr' },
  },
  seoul_jagok: {
    id: 'seoul_jagok',
    name: '서울자곡초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091469' },
    scrape: { kind: 'sen-es', host: 'jagok.sen.es.kr' },
  },
  seoul_cheongdam: {
    id: 'seoul_cheongdam',
    name: '서울청담초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091416' },
    scrape: { kind: 'sen-es', host: 'cheongdam.sen.es.kr' },
  },
  seoul_poi: {
    id: 'seoul_poi',
    name: '서울포이초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091417' },
    scrape: { kind: 'sen-es', host: 'poi.sen.es.kr' },
  },
  seoul_hakdong: {
    id: 'seoul_hakdong',
    name: '서울학동초등학교',
    level: 'elementary',
    region: '서울 강남',
    neis: { atptCode: 'B10', schoolCode: '7091418' },
    scrape: { kind: 'sen-es', host: 'hakdong.sen.es.kr' },
  },
};
