/**
 * 서울 강서구 35교 — Stage 14-11 (2026-05-02), Phase B 네 번째 자치구.
 *
 * 34교 sen.es.kr + 유석초 (서울 prefix 없음, 사립 추정) — host 가 sen.es.kr 라
 * sen-es scraper 그대로 동작. id 충돌 없음.
 */

import type { SchoolConfig } from '../index';

export const GANGSEO_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_gagok: {
    id: 'seoul_gagok',
    name: '서울가곡초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081418' },
    scrape: { kind: 'sen-es', host: 'gagok.sen.es.kr' },
  },
  seoul_kayang: {
    id: 'seoul_kayang',
    name: '서울가양초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081419' },
    scrape: { kind: 'sen-es', host: 'kayang.sen.es.kr' },
  },
  seoul_gaehwa: {
    id: 'seoul_gaehwa',
    name: '서울개화초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081424' },
    scrape: { kind: 'sen-es', host: 'gaehwa.sen.es.kr' },
  },
  seoul_kongjin: {
    id: 'seoul_kongjin',
    name: '서울공진초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081427' },
    scrape: { kind: 'sen-es', host: 'kongjin.sen.es.kr' },
  },
  seoul_konghang: {
    id: 'seoul_konghang',
    name: '서울공항초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081428' },
    scrape: { kind: 'sen-es', host: 'konghang.sen.es.kr' },
  },
  seoul_naebalsan: {
    id: 'seoul_naebalsan',
    name: '서울내발산초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081430' },
    scrape: { kind: 'sen-es', host: 'nbs.sen.es.kr' },
  },
  seoul_deungma: {
    id: 'seoul_deungma',
    name: '서울등마초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081431' },
    scrape: { kind: 'sen-es', host: 'dma.sen.es.kr' },
  },
  seoul_dungmyong: {
    id: 'seoul_dungmyong',
    name: '서울등명초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081432' },
    scrape: { kind: 'sen-es', host: 'dungmyong.sen.es.kr' },
  },
  seoul_deungseo: {
    id: 'seoul_deungseo',
    name: '서울등서초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081433' },
    scrape: { kind: 'sen-es', host: 'deungseo.sen.es.kr' },
  },
  seoul_dungyang: {
    id: 'seoul_dungyang',
    name: '서울등양초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081434' },
    scrape: { kind: 'sen-es', host: 'dungyang.sen.es.kr' },
  },
  seoul_deungwon: {
    id: 'seoul_deungwon',
    name: '서울등원초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081435' },
    scrape: { kind: 'sen-es', host: 'deungwon.sen.es.kr' },
  },
  seoul_deungchon: {
    id: 'seoul_deungchon',
    name: '서울등촌초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081436' },
    scrape: { kind: 'sen-es', host: 'deungchon.sen.es.kr' },
  },
  seoul_deunghyun: {
    id: 'seoul_deunghyun',
    name: '서울등현초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081437' },
    scrape: { kind: 'sen-es', host: 'deunghyun.sen.es.kr' },
  },
  seoul_balsan: {
    id: 'seoul_balsan',
    name: '서울발산초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081441' },
    scrape: { kind: 'sen-es', host: 'balsan.sen.es.kr' },
  },
  seoul_banghwa: {
    id: 'seoul_banghwa',
    name: '서울방화초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081442' },
    scrape: { kind: 'sen-es', host: 'banghwa.sen.es.kr' },
  },
  seoul_baekseok: {
    id: 'seoul_baekseok',
    name: '서울백석초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081443' },
    scrape: { kind: 'sen-es', host: 'bsbs.sen.es.kr' },
  },
  seoul_samjeong: {
    id: 'seoul_samjeong',
    name: '서울삼정초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081444' },
    scrape: { kind: 'sen-es', host: 'esamjeong.sen.es.kr' },
  },
  seoul_songjeong: {
    id: 'seoul_songjeong',
    name: '서울송정초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081446' },
    scrape: { kind: 'sen-es', host: 'sjes.sen.es.kr' },
  },
  seoul_songhwa: {
    id: 'seoul_songhwa',
    name: '서울송화초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081447' },
    scrape: { kind: 'sen-es', host: 'songhwa.sen.es.kr' },
  },
  seoul_sumyeong: {
    id: 'seoul_sumyeong',
    name: '서울수명초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081448' },
    scrape: { kind: 'sen-es', host: 'sumyeong.sen.es.kr' },
  },
  seoul_singok: {
    id: 'seoul_singok',
    name: '서울신곡초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081450' },
    scrape: { kind: 'sen-es', host: 'sg.sen.es.kr' },
  },
  seoul_sinwol: {
    id: 'seoul_sinwol',
    name: '서울신월초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081456' },
    scrape: { kind: 'sen-es', host: 'ssinwol.sen.es.kr' },
  },
  seoul_sinjeong: {
    id: 'seoul_sinjeong',
    name: '서울신정초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081457' },
    scrape: { kind: 'sen-es', host: 'sinjeong.sen.es.kr' },
  },
  seoul_yangcheon: {
    id: 'seoul_yangcheon',
    name: '서울양천초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081463' },
    scrape: { kind: 'sen-es', host: 'yangcheun.sen.es.kr' },
  },
  seoul_yeomkyoung: {
    id: 'seoul_yeomkyoung',
    name: '서울염경초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081466' },
    scrape: { kind: 'sen-es', host: 'yeomkyoung.sen.es.kr' },
  },
  seoul_yeomdong: {
    id: 'seoul_yeomdong',
    name: '서울염동초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081467' },
    scrape: { kind: 'sen-es', host: 'yeomdong.sen.es.kr' },
  },
  seoul_yeomchang: {
    id: 'seoul_yeomchang',
    name: '서울염창초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081468' },
    scrape: { kind: 'sen-es', host: 'yeomchang.sen.es.kr' },
  },
  seoul_ujang: {
    id: 'seoul_ujang',
    name: '서울우장초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081470' },
    scrape: { kind: 'sen-es', host: 'ujang.sen.es.kr' },
  },
  seoul_woljung: {
    id: 'seoul_woljung',
    name: '서울월정초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081471' },
    scrape: { kind: 'sen-es', host: 'woljung.sen.es.kr' },
  },
  seoul_jeonggok: {
    id: 'seoul_jeonggok',
    name: '서울정곡초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081475' },
    scrape: { kind: 'sen-es', host: 'jk.sen.es.kr' },
  },
  seoul_chihyeon: {
    id: 'seoul_chihyeon',
    name: '서울치현초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081478' },
    scrape: { kind: 'sen-es', host: 'chihyeon.sen.es.kr' },
  },
  seoul_topsan: {
    id: 'seoul_topsan',
    name: '서울탑산초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081479' },
    scrape: { kind: 'sen-es', host: 'top.sen.es.kr' },
  },
  seoul_hwagok: {
    id: 'seoul_hwagok',
    name: '서울화곡초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081480' },
    scrape: { kind: 'sen-es', host: 'hwagok.sen.es.kr' },
  },
  seoul_hwail: {
    id: 'seoul_hwail',
    name: '서울화일초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081481' },
    scrape: { kind: 'sen-es', host: 'hwail.sen.es.kr' },
  },
  yooseok: {
    id: 'yooseok',
    name: '유석초등학교',
    level: 'elementary',
    region: '서울 강서',
    neis: { atptCode: 'B10', schoolCode: '7081483' },
    scrape: { kind: 'sen-es', host: 'yooseok.sen.es.kr' },
  },
};
