/**
 * 서울 강동구 29교 — Stage 14-6 (2026-05-02), Phase A 다섯 번째 자치구.
 *
 * 모두 sen.es.kr 패턴. 사립 0교. id 충돌 없음.
 * id 와 subdomain 다른 케이스 다수 (gme, gbe, scd 등 약칭).
 */

import type { SchoolConfig } from '../index';

export const GANGDONG_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_gangdeok: {
    id: 'seoul_gangdeok',
    name: '서울강덕초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130105' },
    scrape: { kind: 'sen-es', host: 'gangdeok.sen.es.kr' },
  },
  seoul_gangdong: {
    id: 'seoul_gangdong',
    name: '서울강동초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130106' },
    scrape: { kind: 'sen-es', host: 'gangdong.sen.es.kr' },
  },
  seoul_gangmyeong: {
    id: 'seoul_gangmyeong',
    name: '서울강명초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130107' },
    scrape: { kind: 'sen-es', host: 'gme.sen.es.kr' },
  },
  seoul_gangbit: {
    id: 'seoul_gangbit',
    name: '서울강빛초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130266' },
    scrape: { kind: 'sen-es', host: 'gbe.sen.es.kr' },
  },
  seoul_gangsol: {
    id: 'seoul_gangsol',
    name: '서울강솔초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130251' },
    scrape: { kind: 'sen-es', host: 'gangsol.sen.es.kr' },
  },
  seoul_gangil: {
    id: 'seoul_gangil',
    name: '서울강일초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130108' },
    scrape: { kind: 'sen-es', host: 'gangil.sen.es.kr' },
  },
  seoul_goduk: {
    id: 'seoul_goduk',
    name: '서울고덕초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130112' },
    scrape: { kind: 'sen-es', host: 'goduk.sen.es.kr' },
  },
  seoul_gomyung: {
    id: 'seoul_gomyung',
    name: '서울고명초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130113' },
    scrape: { kind: 'sen-es', host: 'gomyung.sen.es.kr' },
  },
  seoul_goil: {
    id: 'seoul_goil',
    name: '서울고일초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130114' },
    scrape: { kind: 'sen-es', host: 'goil.sen.es.kr' },
  },
  seoul_gohyeon: {
    id: 'seoul_gohyeon',
    name: '서울고현초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130264' },
    scrape: { kind: 'sen-es', host: 'gohyeon.sen.es.kr' },
  },
  seoul_gildong: {
    id: 'seoul_gildong',
    name: '서울길동초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130115' },
    scrape: { kind: 'sen-es', host: 'gildong.sen.es.kr' },
  },
  seoul_daemyeong: {
    id: 'seoul_daemyeong',
    name: '서울대명초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130117' },
    scrape: { kind: 'sen-es', host: 'daemyeong.sen.es.kr' },
  },
  seoul_doonchon: {
    id: 'seoul_doonchon',
    name: '서울둔촌초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130118' },
    scrape: { kind: 'sen-es', host: 'doonchon.sen.es.kr' },
  },
  seoul_myungduk: {
    id: 'seoul_myungduk',
    name: '서울명덕초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130120' },
    scrape: { kind: 'sen-es', host: 'myungduk.sen.es.kr' },
  },
  seoul_myongwon: {
    id: 'seoul_myongwon',
    name: '서울명원초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130121' },
    scrape: { kind: 'sen-es', host: 'myongwon.sen.es.kr' },
  },
  seoul_myeongil: {
    id: 'seoul_myeongil',
    name: '서울명일초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130122' },
    scrape: { kind: 'sen-es', host: 'myeongil.sen.es.kr' },
  },
  seoul_myogok: {
    id: 'seoul_myogok',
    name: '서울묘곡초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130123' },
    scrape: { kind: 'sen-es', host: 'myogok.sen.es.kr' },
  },
  seoul_sangil: {
    id: 'seoul_sangil',
    name: '서울상일초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130131' },
    scrape: { kind: 'sen-es', host: 'seoulsangil.sen.es.kr' },
  },
  seoul_sunrin: {
    id: 'seoul_sunrin',
    name: '서울선린초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130133' },
    scrape: { kind: 'sen-es', host: 'sunrin.sen.es.kr' },
  },
  seoul_sunsa: {
    id: 'seoul_sunsa',
    name: '서울선사초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130134' },
    scrape: { kind: 'sen-es', host: 'sunsa.sen.es.kr' },
  },
  seoul_seongnae: {
    id: 'seoul_seongnae',
    name: '서울성내초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130135' },
    scrape: { kind: 'sen-es', host: 'seongnae.sen.es.kr' },
  },
  seoul_seongil: {
    id: 'seoul_seongil',
    name: '서울성일초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130136' },
    scrape: { kind: 'sen-es', host: 'seongil.sen.es.kr' },
  },
  seoul_shinmyung: {
    id: 'seoul_shinmyung',
    name: '서울신명초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130142' },
    scrape: { kind: 'sen-es', host: 'shinmyung.sen.es.kr' },
  },
  seoul_shinam: {
    id: 'seoul_shinam',
    name: '서울신암초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130143' },
    scrape: { kind: 'sen-es', host: 'shinam.sen.es.kr' },
  },
  seoul_wirye: {
    id: 'seoul_wirye',
    name: '서울위례초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130149' },
    scrape: { kind: 'sen-es', host: 'wirye.sen.es.kr' },
  },
  seoul_cheondong: {
    id: 'seoul_cheondong',
    name: '서울천동초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130157' },
    scrape: { kind: 'sen-es', host: 'scd.sen.es.kr' },
  },
  seoul_chunil: {
    id: 'seoul_chunil',
    name: '서울천일초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130158' },
    scrape: { kind: 'sen-es', host: 'chunil.sen.es.kr' },
  },
  seoul_chunho: {
    id: 'seoul_chunho',
    name: '서울천호초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130159' },
    scrape: { kind: 'sen-es', host: 'chunho.sen.es.kr' },
  },
  seoul_hansan: {
    id: 'seoul_hansan',
    name: '서울한산초등학교',
    level: 'elementary',
    region: '서울 강동',
    neis: { atptCode: 'B10', schoolCode: '7130164' },
    scrape: { kind: 'sen-es', host: 'hansan.sen.es.kr' },
  },
};
