/**
 * 서울 구로구 27교 — Stage 14-9 (2026-05-02), Phase B 두 번째 자치구.
 *
 * 26교 sen.es.kr + 1교 (천이초) HMPG_ADRES 빈값 → scrape 생략 (NEIS 메뉴만).
 * id 충돌 없음.
 */

import type { SchoolConfig } from '../index';

export const GURO_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_kaemyong: {
    id: 'seoul_kaemyong',
    name: '서울개명초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041101' },
    scrape: { kind: 'sen-es', host: 'kaemyong.sen.es.kr' },
  },
  seoul_gaebong: {
    id: 'seoul_gaebong',
    name: '서울개봉초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041102' },
    scrape: { kind: 'sen-es', host: 'gaebong.sen.es.kr' },
  },
  seoul_gaewoong: {
    id: 'seoul_gaewoong',
    name: '서울개웅초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041103' },
    scrape: { kind: 'sen-es', host: 'gaewoong.sen.es.kr' },
  },
  seoul_kohsan: {
    id: 'seoul_kohsan',
    name: '서울고산초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041104' },
    scrape: { kind: 'sen-es', host: 'kohsan.sen.es.kr' },
  },
  seoul_gowon: {
    id: 'seoul_gowon',
    name: '서울고원초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041105' },
    scrape: { kind: 'sen-es', host: 'gowon.sen.es.kr' },
  },
  seoul_gocheok: {
    id: 'seoul_gocheok',
    name: '서울고척초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041106' },
    scrape: { kind: 'sen-es', host: 'gocheok.sen.es.kr' },
  },
  seoul_guronam: {
    id: 'seoul_guronam',
    name: '서울구로남초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041107' },
    scrape: { kind: 'sen-es', host: 'guronam.sen.es.kr' },
  },
  seoul_guro: {
    id: 'seoul_guro',
    name: '서울구로초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041108' },
    scrape: { kind: 'sen-es', host: 'guro.sen.es.kr' },
  },
  seoul_guil: {
    id: 'seoul_guil',
    name: '서울구일초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041109' },
    scrape: { kind: 'sen-es', host: 'guil.sen.es.kr' },
  },
  seoul_dukeui: {
    id: 'seoul_dukeui',
    name: '서울덕의초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041120' },
    scrape: { kind: 'sen-es', host: 'dukeui.sen.es.kr' },
  },
  seoul_dongguro: {
    id: 'seoul_dongguro',
    name: '서울동구로초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041124' },
    scrape: { kind: 'sen-es', host: 'dongguro.sen.es.kr' },
  },
  seoul_maebong: {
    id: 'seoul_maebong',
    name: '서울매봉초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041126' },
    scrape: { kind: 'sen-es', host: 'maebong.sen.es.kr' },
  },
  seoul_mirae: {
    id: 'seoul_mirae',
    name: '서울미래초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041131' },
    scrape: { kind: 'sen-es', host: 'mirae.sen.es.kr' },
  },
  seoul_segok: {
    id: 'seoul_segok',
    name: '서울세곡초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041134' },
    scrape: { kind: 'sen-es', host: 'segok.sen.es.kr' },
  },
  seoul_singuro: {
    id: 'seoul_singuro',
    name: '서울신구로초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041136' },
    scrape: { kind: 'sen-es', host: 'singuro.sen.es.kr' },
  },
  seoul_sindorim: {
    id: 'seoul_sindorim',
    name: '서울신도림초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041138' },
    scrape: { kind: 'sen-es', host: 'sindorim.sen.es.kr' },
  },
  seoul_sinmirim: {
    id: 'seoul_sinmirim',
    name: '서울신미림초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041139' },
    scrape: { kind: 'sen-es', host: 'sinmirim.sen.es.kr' },
  },
  seoul_youngseo: {
    id: 'seoul_youngseo',
    name: '서울영서초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041149' },
    scrape: { kind: 'sen-es', host: 'youngseo.sen.es.kr' },
  },
  seoul_youngil: {
    id: 'seoul_youngil',
    name: '서울영일초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041152' },
    scrape: { kind: 'sen-es', host: 'syoungil.sen.es.kr' },
  },
  seoul_oryunam: {
    id: 'seoul_oryunam',
    name: '서울오류남초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041154' },
    scrape: { kind: 'sen-es', host: 'oryunam.sen.es.kr' },
  },
  seoul_oryu: {
    id: 'seoul_oryu',
    name: '서울오류초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041155' },
    scrape: { kind: 'sen-es', host: 'oryu.sen.es.kr' },
  },
  seoul_ojung: {
    id: 'seoul_ojung',
    name: '서울오정초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041156' },
    scrape: { kind: 'sen-es', host: 'ojung.sen.es.kr' },
  },
  seoul_onsu: {
    id: 'seoul_onsu',
    name: '서울온수초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041157' },
    scrape: { kind: 'sen-es', host: 'onsu.sen.es.kr' },
  },
  seoul_cheonwang: {
    id: 'seoul_cheonwang',
    name: '서울천왕초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041209' },
    scrape: { kind: 'sen-es', host: 'cheonwang.sen.es.kr' },
  },
  seoul_cheoni: {
    id: 'seoul_cheoni',
    name: '서울천이초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041254' },
    // scrape 생략 — NEIS HMPG_ADRES 빈값. 메뉴만 노출, 사진 미지원.
  },
  seoul_skyforest: {
    id: 'seoul_skyforest',
    name: '서울하늘숲초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041266' },
    scrape: { kind: 'sen-es', host: 'skyf.sen.es.kr' },
  },
  seoul_hangdong: {
    id: 'seoul_hangdong',
    name: '서울항동초등학교',
    level: 'elementary',
    region: '서울 구로',
    neis: { atptCode: 'B10', schoolCode: '7041267' },
    scrape: { kind: 'sen-es', host: 'hangdong.sen.es.kr' },
  },
};
