/**
 * 서울 광진구 21교 — Stage 14-21 (2026-05-03), Phase D 마지막 자치구.
 *
 * 20교 sen.es.kr + 1교 (경복초 사립) host kbes.kr → scrape 생략.
 * 성동초·세종초 등 사립도 host sen.es.kr 라 등록.
 */

import type { SchoolConfig } from '../index';

export const GWANGJIN_SCHOOLS: Record<string, SchoolConfig> = {
  gyeongbok_es: {
    id: 'gyeongbok_es',
    name: '경복초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134077' },
    // scrape 생략 — host = www.kbes.kr (사립). NEIS 메뉴만.
  },
  seoul_gwangnam: {
    id: 'seoul_gwangnam',
    name: '서울광남초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134081' },
    scrape: { kind: 'sen-es', host: 'gwangnam.sen.es.kr' },
  },
  seoul_kwangjang: {
    id: 'seoul_kwangjang',
    name: '서울광장초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134082' },
    scrape: { kind: 'sen-es', host: 'kwangjang.sen.es.kr' },
  },
  seoul_gwangjin: {
    id: 'seoul_gwangjin',
    name: '서울광진초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134083' },
    scrape: { kind: 'sen-es', host: 'gwangjin.sen.es.kr' },
  },
  seoul_gunam: {
    id: 'seoul_gunam',
    name: '서울구남초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134084' },
    scrape: { kind: 'sen-es', host: 'gunam.sen.es.kr' },
  },
  seoul_guui: {
    id: 'seoul_guui',
    name: '서울구의초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134085' },
    scrape: { kind: 'sen-es', host: 'guui.sen.es.kr' },
  },
  seoul_dongeui: {
    id: 'seoul_dongeui',
    name: '서울동의초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134090' },
    scrape: { kind: 'sen-es', host: 'dongeui.sen.es.kr' },
  },
  seoul_dongja: {
    id: 'seoul_dongja',
    name: '서울동자초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134091' },
    scrape: { kind: 'sen-es', host: 'dongja.sen.es.kr' },
  },
  seoul_seongja: {
    id: 'seoul_seongja',
    name: '서울성자초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134097' },
    scrape: { kind: 'sen-es', host: 'seongja.sen.es.kr' },
  },
  seoul_sinyang: {
    id: 'seoul_sinyang',
    name: '서울신양초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134099' },
    scrape: { kind: 'sen-es', host: 'sinyang.sen.es.kr' },
  },
  seoul_sinja: {
    id: 'seoul_sinja',
    name: '서울신자초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134100' },
    scrape: { kind: 'sen-es', host: 'sinja.sen.es.kr' },
  },
  seoul_yangnam: {
    id: 'seoul_yangnam',
    name: '서울양남초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134101' },
    scrape: { kind: 'sen-es', host: 's-yangnam.sen.es.kr' },
  },
  seoul_yangjin: {
    id: 'seoul_yangjin',
    name: '서울양진초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134102' },
    scrape: { kind: 'sen-es', host: 'yjs.sen.es.kr' },
  },
  seoul_yonggok: {
    id: 'seoul_yonggok',
    name: '서울용곡초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134105' },
    scrape: { kind: 'sen-es', host: 'yonggok.sen.es.kr' },
  },
  seoul_yongma: {
    id: 'seoul_yongma',
    name: '서울용마초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134107' },
    scrape: { kind: 'sen-es', host: 'ymc.sen.es.kr' },
  },
  seoul_jayang: {
    id: 'seoul_jayang',
    name: '서울자양초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134109' },
    scrape: { kind: 'sen-es', host: 'jayang.sen.es.kr' },
  },
  seoul_jangan: {
    id: 'seoul_jangan',
    name: '서울장안초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134110' },
    scrape: { kind: 'sen-es', host: 'jangan.sen.es.kr' },
  },
  seoul_junggwang: {
    id: 'seoul_junggwang',
    name: '서울중광초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134111' },
    scrape: { kind: 'sen-es', host: 'jkschool.sen.es.kr' },
  },
  seoul_jungma: {
    id: 'seoul_jungma',
    name: '서울중마초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134112' },
    scrape: { kind: 'sen-es', host: 'jungma.sen.es.kr' },
  },
  seoul_seongdong: {
    id: 'seoul_seongdong',
    name: '성동초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134116' },
    scrape: { kind: 'sen-es', host: 'sungdong.sen.es.kr' },
  },
  seoul_sejong: {
    id: 'seoul_sejong',
    name: '세종초등학교',
    level: 'elementary',
    region: '서울 광진',
    neis: { atptCode: 'B10', schoolCode: '7134117' },
    scrape: { kind: 'sen-es', host: 'sejong.sen.es.kr' },
  },
};
