/**
 * 서울 관악구 22교 — Stage 14-3 (2026-05-02), Phase A 두 번째 자치구.
 *
 * 모두 sen.es.kr 패턴. 사립 0교.
 * NEIS HMPG_ADRES 일괄 추출값 그대로 (id 와 subdomain 다른 케이스 다수 —
 * seoul-kwanak·seoulguam·seoulnambu·seoulsinwoo·sss·sillim·sss 등).
 */

import type { SchoolConfig } from '../index';

export const GWANAK_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_kwanak: {
    id: 'seoul_kwanak',
    name: '서울관악초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132081' },
    scrape: { kind: 'sen-es', host: 'seoul-kwanak.sen.es.kr' },
  },
  seoul_guam: {
    id: 'seoul_guam',
    name: '서울구암초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132082' },
    scrape: { kind: 'sen-es', host: 'seoulguam.sen.es.kr' },
  },
  seoul_nangok: {
    id: 'seoul_nangok',
    name: '서울난곡초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132083' },
    scrape: { kind: 'sen-es', host: 'nangok.sen.es.kr' },
  },
  seoul_nanwoo: {
    id: 'seoul_nanwoo',
    name: '서울난우초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132084' },
    scrape: { kind: 'sen-es', host: 'nanwoo.sen.es.kr' },
  },
  seoul_nanhyang: {
    id: 'seoul_nanhyang',
    name: '서울난향초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132085' },
    scrape: { kind: 'sen-es', host: 'nanhyang.sen.es.kr' },
  },
  seoul_nambu: {
    id: 'seoul_nambu',
    name: '서울남부초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132086' },
    scrape: { kind: 'sen-es', host: 'seoulnambu.sen.es.kr' },
  },
  seoul_danggok: {
    id: 'seoul_danggok',
    name: '서울당곡초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132090' },
    scrape: { kind: 'sen-es', host: 'danggok.sen.es.kr' },
  },
  seoul_misung: {
    id: 'seoul_misung',
    name: '서울미성초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132094' },
    scrape: { kind: 'sen-es', host: 'misung.sen.es.kr' },
  },
  seoul_bongcheon: {
    id: 'seoul_bongcheon',
    name: '서울봉천초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132097' },
    scrape: { kind: 'sen-es', host: 'bongcheon.sen.es.kr' },
  },
  seoul_bonghyun: {
    id: 'seoul_bonghyun',
    name: '서울봉현초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132098' },
    scrape: { kind: 'sen-es', host: 'bonghyun.sen.es.kr' },
  },
  seoul_sadang: {
    id: 'seoul_sadang',
    name: '서울사당초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132099' },
    scrape: { kind: 'sen-es', host: 'sadang.sen.es.kr' },
  },
  seoul_samseong: {
    id: 'seoul_samseong',
    name: '서울삼성초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132100' },
    scrape: { kind: 'sen-es', host: 'samseong.sen.es.kr' },
  },
  seoul_sillim: {
    id: 'seoul_sillim',
    name: '서울신림초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132106' },
    scrape: { kind: 'sen-es', host: 'sillim.sen.es.kr' },
  },
  seoul_sinbong: {
    id: 'seoul_sinbong',
    name: '서울신봉초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132107' },
    scrape: { kind: 'sen-es', host: 'sinbong.sen.es.kr' },
  },
  seoul_sinseong: {
    id: 'seoul_sinseong',
    name: '서울신성초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132109' },
    scrape: { kind: 'sen-es', host: 'sss.sen.es.kr' },
  },
  seoul_sinwoo: {
    id: 'seoul_sinwoo',
    name: '서울신우초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132110' },
    scrape: { kind: 'sen-es', host: 'seoulsinwoo.sen.es.kr' },
  },
  seoul_wondang: {
    id: 'seoul_wondang',
    name: '서울원당초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132113' },
    scrape: { kind: 'sen-es', host: 'wondang.sen.es.kr' },
  },
  seoul_wonshin: {
    id: 'seoul_wonshin',
    name: '서울원신초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132114' },
    scrape: { kind: 'sen-es', host: 'wonshin.sen.es.kr' },
  },
  seoul_euncheon: {
    id: 'seoul_euncheon',
    name: '서울은천초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132116' },
    scrape: { kind: 'sen-es', host: 'euncheon.sen.es.kr' },
  },
  seoul_inhun: {
    id: 'seoul_inhun',
    name: '서울인헌초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132117' },
    scrape: { kind: 'sen-es', host: 'inhun.sen.es.kr' },
  },
  seoul_jowon: {
    id: 'seoul_jowon',
    name: '서울조원초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132118' },
    scrape: { kind: 'sen-es', host: 'jowon.sen.es.kr' },
  },
  seoul_chungryong: {
    id: 'seoul_chungryong',
    name: '서울청룡초등학교',
    level: 'elementary',
    region: '서울 관악',
    neis: { atptCode: 'B10', schoolCode: '7132119' },
    scrape: { kind: 'sen-es', host: 'chungryong.sen.es.kr' },
  },
};
