/**
 * 서울 중랑구 24교 — Stage 14-23 (2026-05-03), Phase E 두 번째 자치구.
 *
 * 23교 sen.es.kr + 1교 (금성초 사립) host kumsung.net → scrape 생략.
 */

import type { SchoolConfig } from '../index';

export const JUNGNANG_SCHOOLS: Record<string, SchoolConfig> = {
  kumsung_es: {
    id: 'kumsung_es',
    name: '금성초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021080' },
    // scrape 생략 — host = www.kumsung.net (사립). NEIS 메뉴만.
  },
  seoul_dongwon: {
    id: 'seoul_dongwon',
    name: '서울동원초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021085' },
    scrape: { kind: 'sen-es', host: 'dongwon.sen.es.kr' },
  },
  seoul_mangwoo: {
    id: 'seoul_mangwoo',
    name: '서울망우초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021086' },
    scrape: { kind: 'sen-es', host: 'mangwoo.sen.es.kr' },
  },
  seoul_myunnam: {
    id: 'seoul_myunnam',
    name: '서울면남초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021087' },
    scrape: { kind: 'sen-es', host: 'myunnam.sen.es.kr' },
  },
  seoul_myeondong: {
    id: 'seoul_myeondong',
    name: '서울면동초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021088' },
    scrape: { kind: 'sen-es', host: 'myeondong.sen.es.kr' },
  },
  seoul_myeonmok: {
    id: 'seoul_myeonmok',
    name: '서울면목초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021089' },
    scrape: { kind: 'sen-es', host: 'myeonmok.sen.es.kr' },
  },
  seoul_myeonbuk: {
    id: 'seoul_myeonbuk',
    name: '서울면북초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021090' },
    scrape: { kind: 'sen-es', host: 'myeonbuk.sen.es.kr' },
  },
  seoul_myeonil: {
    id: 'seoul_myeonil',
    name: '서울면일초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021091' },
    scrape: { kind: 'sen-es', host: 'myeonil.sen.es.kr' },
  },
  seoul_myunjoong: {
    id: 'seoul_myunjoong',
    name: '서울면중초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021092' },
    scrape: { kind: 'sen-es', host: 'myunjoong.sen.es.kr' },
  },
  seoul_mookdong: {
    id: 'seoul_mookdong',
    name: '서울묵동초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021093' },
    scrape: { kind: 'sen-es', host: 'mookdong.sen.es.kr' },
  },
  seoul_mookhyun: {
    id: 'seoul_mookhyun',
    name: '서울묵현초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021094' },
    scrape: { kind: 'sen-es', host: 'mh.sen.es.kr' },
  },
  seoul_bonghwa: {
    id: 'seoul_bonghwa',
    name: '서울봉화초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021096' },
    scrape: { kind: 'sen-es', host: 'bonghwa.sen.es.kr' },
  },
  seoul_sangbong: {
    id: 'seoul_sangbong',
    name: '서울상봉초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021097' },
    scrape: { kind: 'sen-es', host: 'sang-bong.sen.es.kr' },
  },
  seoul_saesol: {
    id: 'seoul_saesol',
    name: '서울새솔초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021181' },
    scrape: { kind: 'sen-es', host: 'saesol.sen.es.kr' },
  },
  seoul_sinnae: {
    id: 'seoul_sinnae',
    name: '서울신내초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021098' },
    scrape: { kind: 'sen-es', host: 'sinne.sen.es.kr' },
  },
  seoul_sinmook: {
    id: 'seoul_sinmook',
    name: '서울신묵초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021100' },
    scrape: { kind: 'sen-es', host: 'sinmook.sen.es.kr' },
  },
  seoul_shinhyun: {
    id: 'seoul_shinhyun',
    name: '서울신현초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021101' },
    scrape: { kind: 'sen-es', host: 'shinhyun.sen.es.kr' },
  },
  seoul_yangwonsoop: {
    id: 'seoul_yangwonsoop',
    name: '서울양원숲초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021205' },
    scrape: { kind: 'sen-es', host: 'yangwonsoop.sen.es.kr' },
  },
  seoul_wonmuk: {
    id: 'seoul_wonmuk',
    name: '서울원묵초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021104' },
    scrape: { kind: 'sen-es', host: 'wonmuk.sen.es.kr' },
  },
  seoul_jungkok: {
    id: 'seoul_jungkok',
    name: '서울중곡초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021111' },
    scrape: { kind: 'sen-es', host: 'cg.sen.es.kr' },
  },
  seoul_jungnang: {
    id: 'seoul_jungnang',
    name: '서울중랑초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021112' },
    scrape: { kind: 'sen-es', host: 'jungnang.sen.es.kr' },
  },
  seoul_joongmok: {
    id: 'seoul_joongmok',
    name: '서울중목초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021113' },
    scrape: { kind: 'sen-es', host: 'joongmok.sen.es.kr' },
  },
  seoul_junghwa: {
    id: 'seoul_junghwa',
    name: '서울중화초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021114' },
    scrape: { kind: 'sen-es', host: 'junghwa.sen.es.kr' },
  },
  seoul_jungheung: {
    id: 'seoul_jungheung',
    name: '서울중흥초등학교',
    level: 'elementary',
    region: '서울 중랑',
    neis: { atptCode: 'B10', schoolCode: '7021115' },
    scrape: { kind: 'sen-es', host: 'jung-heung.sen.es.kr' },
  },
};
