/**
 * 서울 마포구 22교 — Stage 14-14 (2026-05-02), Phase C 첫 자치구.
 *
 * 모두 sen.es.kr. 홍익대 부속 1교 (서울 prefix 없는 사립) 도 host sen.es.kr.
 */

import type { SchoolConfig } from '../index';

export const MAPO_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_kongduck: {
    id: 'seoul_kongduck',
    name: '서울공덕초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031114' },
    scrape: { kind: 'sen-es', host: 'kongduck.sen.es.kr' },
  },
  seoul_donggyo: {
    id: 'seoul_donggyo',
    name: '서울동교초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031122' },
    scrape: { kind: 'sen-es', host: 'donggyo.sen.es.kr' },
  },
  seoul_mapo: {
    id: 'seoul_mapo',
    name: '서울마포초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031123' },
    scrape: { kind: 'sen-es', host: 'mapo.sen.es.kr' },
  },
  seoul_mangwon: {
    id: 'seoul_mangwon',
    name: '서울망원초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031124' },
    scrape: { kind: 'sen-es', host: 'mangwon.sen.es.kr' },
  },
  seoul_sangam: {
    id: 'seoul_sangam',
    name: '서울상암초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031131' },
    scrape: { kind: 'sen-es', host: 'sangam.sen.es.kr' },
  },
  seoul_sangji: {
    id: 'seoul_sangji',
    name: '서울상지초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031132' },
    scrape: { kind: 'sen-es', host: 'seoulsangji.sen.es.kr' },
  },
  seoul_seogang: {
    id: 'seoul_seogang',
    name: '서울서강초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031133' },
    scrape: { kind: 'sen-es', host: 'seogang.sen.es.kr' },
  },
  seoul_seokyo: {
    id: 'seoul_seokyo',
    name: '서울서교초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031134' },
    scrape: { kind: 'sen-es', host: 'seokyo.sen.es.kr' },
  },
  seoul_sangsan_mp: {
    id: 'seoul_sangsan_mp',
    name: '서울성산초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031136' },
    scrape: { kind: 'sen-es', host: 'ssc.sen.es.kr' },
  },
  seoul_seongseo: {
    id: 'seoul_seongseo',
    name: '서울성서초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031137' },
    scrape: { kind: 'sen-es', host: 'sseo.sen.es.kr' },
  },
  seoul_sungwon: {
    id: 'seoul_sungwon',
    name: '서울성원초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031138' },
    scrape: { kind: 'sen-es', host: 'sungwon.sen.es.kr' },
  },
  seoul_soeui: {
    id: 'seoul_soeui',
    name: '서울소의초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031139' },
    scrape: { kind: 'sen-es', host: 'soeui.sen.es.kr' },
  },
  seoul_sinbuk: {
    id: 'seoul_sinbuk',
    name: '서울신북초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031142' },
    scrape: { kind: 'sen-es', host: 'sinbuk.sen.es.kr' },
  },
  seoul_sinseok: {
    id: 'seoul_sinseok',
    name: '서울신석초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031144' },
    scrape: { kind: 'sen-es', host: 'sinseok.sen.es.kr' },
  },
  seoul_ahyun: {
    id: 'seoul_ahyun',
    name: '서울아현초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031145' },
    scrape: { kind: 'sen-es', host: 'ahyun.sen.es.kr' },
  },
  seoul_yeomri: {
    id: 'seoul_yeomri',
    name: '서울염리초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031154' },
    scrape: { kind: 'sen-es', host: 'yeomri.sen.es.kr' },
  },
  seoul_yonggang: {
    id: 'seoul_yonggang',
    name: '서울용강초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031155' },
    scrape: { kind: 'sen-es', host: 'yonggang.sen.es.kr' },
  },
  seoul_jungdong: {
    id: 'seoul_jungdong',
    name: '서울중동초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031161' },
    scrape: { kind: 'sen-es', host: 'jungdong.sen.es.kr' },
  },
  seoul_changchon: {
    id: 'seoul_changchon',
    name: '서울창천초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031165' },
    scrape: { kind: 'sen-es', host: 'changchon.sen.es.kr' },
  },
  seoul_haneul: {
    id: 'seoul_haneul',
    name: '서울하늘초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031231' },
    scrape: { kind: 'sen-es', host: 'sky.sen.es.kr' },
  },
  seoul_hanseo: {
    id: 'seoul_hanseo',
    name: '서울한서초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031166' },
    scrape: { kind: 'sen-es', host: 'hanseo.sen.es.kr' },
  },
  seoul_hongik: {
    id: 'seoul_hongik',
    name: '홍익대학교사범대학부속초등학교',
    level: 'elementary',
    region: '서울 마포',
    neis: { atptCode: 'B10', schoolCode: '7031177' },
    scrape: { kind: 'sen-es', host: 'hongik.sen.es.kr' },
  },
};
