/**
 * 서울 노원구 42교 — Stage 14-12 (2026-05-02), Phase B 다섯 번째 자치구.
 *
 * 모두 sen.es.kr. 서울 prefix 없는 사립 4교 (상명·청원·태강삼육·화랑) 도 host
 * 가 sen.es.kr 이라 sen-es scraper 동작. id 충돌 없음 (chonggye 와 한자 동일하나
 * 노원구는 `seoul_chonggye_nw`, 의왕은 `chonggye`).
 */

import type { SchoolConfig } from '../index';

export const NOWON_SCHOOLS: Record<string, SchoolConfig> = {
  smcho: {
    id: 'smcho',
    name: '상명초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051110' },
    scrape: { kind: 'sen-es', host: 'smcho.sen.es.kr' },
  },
  seoul_kyesang: {
    id: 'seoul_kyesang',
    name: '서울계상초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051112' },
    scrape: { kind: 'sen-es', host: 'kyesang.sen.es.kr' },
  },
  seoul_gongrung: {
    id: 'seoul_gongrung',
    name: '서울공릉초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051113' },
    scrape: { kind: 'sen-es', host: 'gongrung.sen.es.kr' },
  },
  seoul_gongyeon: {
    id: 'seoul_gongyeon',
    name: '서울공연초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051114' },
    scrape: { kind: 'sen-es', host: 'gongyeon.sen.es.kr' },
  },
  seoul_nowon: {
    id: 'seoul_nowon',
    name: '서울노원초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051115' },
    scrape: { kind: 'sen-es', host: 'nowon.sen.es.kr' },
  },
  seoul_noil: {
    id: 'seoul_noil',
    name: '서울노일초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051116' },
    scrape: { kind: 'sen-es', host: 'noil.sen.es.kr' },
  },
  seoul_nokcheon: {
    id: 'seoul_nokcheon',
    name: '서울녹천초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051117' },
    scrape: { kind: 'sen-es', host: 'nokcheon.sen.es.kr' },
  },
  seoul_danghyeon: {
    id: 'seoul_danghyeon',
    name: '서울당현초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051119' },
    scrape: { kind: 'sen-es', host: 'danghyeon.sen.es.kr' },
  },
  seoul_deokam: {
    id: 'seoul_deokam',
    name: '서울덕암초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051120' },
    scrape: { kind: 'sen-es', host: 'deokam.sen.es.kr' },
  },
  seoul_dongil: {
    id: 'seoul_dongil',
    name: '서울동일초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051122' },
    scrape: { kind: 'sen-es', host: 'dongil.sen.es.kr' },
  },
  seoul_bulam: {
    id: 'seoul_bulam',
    name: '서울불암초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051125' },
    scrape: { kind: 'sen-es', host: 'bulam.sen.es.kr' },
  },
  seoul_sanggyeong: {
    id: 'seoul_sanggyeong',
    name: '서울상경초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051126' },
    scrape: { kind: 'sen-es', host: 'sanggyeong.sen.es.kr' },
  },
  seoul_sanggye: {
    id: 'seoul_sanggye',
    name: '서울상계초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051127' },
    scrape: { kind: 'sen-es', host: 'sanggye.sen.es.kr' },
  },
  seoul_sanggok: {
    id: 'seoul_sanggok',
    name: '서울상곡초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051128' },
    scrape: { kind: 'sen-es', host: 'sanggok.sen.es.kr' },
  },
  seoul_sangsoo: {
    id: 'seoul_sangsoo',
    name: '서울상수초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051129' },
    scrape: { kind: 'sen-es', host: 'sangsoo.sen.es.kr' },
  },
  seoul_sangwon: {
    id: 'seoul_sangwon',
    name: '서울상원초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051130' },
    scrape: { kind: 'sen-es', host: 'sangwon.sen.es.kr' },
  },
  seoul_sangwol: {
    id: 'seoul_sangwol',
    name: '서울상월초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051131' },
    scrape: { kind: 'sen-es', host: 'sw.sen.es.kr' },
  },
  seoul_sangcheon: {
    id: 'seoul_sangcheon',
    name: '서울상천초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051132' },
    scrape: { kind: 'sen-es', host: 'sangcheon.sen.es.kr' },
  },
  seoul_sungok: {
    id: 'seoul_sungok',
    name: '서울선곡초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051133' },
    scrape: { kind: 'sen-es', host: 'sungok.sen.es.kr' },
  },
  seoul_surak: {
    id: 'seoul_surak',
    name: '서울수락초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051134' },
    scrape: { kind: 'sen-es', host: 'surak.sen.es.kr' },
  },
  seoul_suam: {
    id: 'seoul_suam',
    name: '서울수암초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051135' },
    scrape: { kind: 'sen-es', host: 'suam.sen.es.kr' },
  },
  seoul_singye: {
    id: 'seoul_singye',
    name: '서울신계초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051137' },
    scrape: { kind: 'sen-es', host: 'singye.sen.es.kr' },
  },
  seoul_sinsanggye: {
    id: 'seoul_sinsanggye',
    name: '서울신상계초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051139' },
    scrape: { kind: 'sen-es', host: 'sinsanggye.sen.es.kr' },
  },
  seoul_yeonji: {
    id: 'seoul_yeonji',
    name: '서울연지초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051144' },
    scrape: { kind: 'sen-es', host: 'seoulyeonji.sen.es.kr' },
  },
  seoul_yeonchon: {
    id: 'seoul_yeonchon',
    name: '서울연촌초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051145' },
    scrape: { kind: 'sen-es', host: 'yeonchon.sen.es.kr' },
  },
  seoul_ongok: {
    id: 'seoul_ongok',
    name: '서울온곡초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051147' },
    scrape: { kind: 'sen-es', host: 'ongok.sen.es.kr' },
  },
  seoul_yongdong_nw: {
    id: 'seoul_yongdong_nw',
    name: '서울용동초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051148' },
    scrape: { kind: 'sen-es', host: 'yongdong.sen.es.kr' },
  },
  seoul_yongwon: {
    id: 'seoul_yongwon',
    name: '서울용원초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051149' },
    scrape: { kind: 'sen-es', host: 'yong1.sen.es.kr' },
  },
  seoul_wonkwang: {
    id: 'seoul_wonkwang',
    name: '서울원광초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051150' },
    scrape: { kind: 'sen-es', host: 'wonkwang.sen.es.kr' },
  },
  seoul_wolgye: {
    id: 'seoul_wolgye',
    name: '서울월계초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051151' },
    scrape: { kind: 'sen-es', host: 'wolgye.sen.es.kr' },
  },
  seoul_eulji: {
    id: 'seoul_eulji',
    name: '서울을지초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051153' },
    scrape: { kind: 'sen-es', host: 'eulji.sen.es.kr' },
  },
  seoul_junggye: {
    id: 'seoul_junggye',
    name: '서울중계초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051155' },
    scrape: { kind: 'sen-es', host: 'jg.sen.es.kr' },
  },
  seoul_jungwon: {
    id: 'seoul_jungwon',
    name: '서울중원초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051156' },
    scrape: { kind: 'sen-es', host: 'jungwon.sen.es.kr' },
  },
  seoul_jungpyong: {
    id: 'seoul_jungpyong',
    name: '서울중평초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051157' },
    scrape: { kind: 'sen-es', host: 'jungpyong.sen.es.kr' },
  },
  seoul_joonghyun: {
    id: 'seoul_joonghyun',
    name: '서울중현초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051158' },
    scrape: { kind: 'sen-es', host: 'joonghyun.sen.es.kr' },
  },
  seoul_chonggye_nw: {
    id: 'seoul_chonggye_nw',
    name: '서울청계초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051165' },
    scrape: { kind: 'sen-es', host: 'scg.sen.es.kr' },
  },
  seoul_taerang: {
    id: 'seoul_taerang',
    name: '서울태랑초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051167' },
    scrape: { kind: 'sen-es', host: 'taerang.sen.es.kr' },
  },
  seoul_taereung: {
    id: 'seoul_taereung',
    name: '서울태릉초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051168' },
    scrape: { kind: 'sen-es', host: 'taereung.sen.es.kr' },
  },
  seoul_hancheon: {
    id: 'seoul_hancheon',
    name: '서울한천초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051169' },
    scrape: { kind: 'sen-es', host: 'hancheon.sen.es.kr' },
  },
  cheongwon: {
    id: 'cheongwon',
    name: '청원초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051170' },
    scrape: { kind: 'sen-es', host: 'cheongwon.sen.es.kr' },
  },
  taegang: {
    id: 'taegang',
    name: '태강삼육초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051171' },
    scrape: { kind: 'sen-es', host: 'taegang.sen.es.kr' },
  },
  hwarang: {
    id: 'hwarang',
    name: '화랑초등학교',
    level: 'elementary',
    region: '서울 노원',
    neis: { atptCode: 'B10', schoolCode: '7051173' },
    scrape: { kind: 'sen-es', host: 'hwarang-s.sen.es.kr' },
  },
};
