/**
 * 서울 서초구 24교 — Stage 14 ~ 14-1-2 등록.
 *
 * 23교 sen.es.kr (Stage 14-1) + 1교 사립 (Stage 14-1-2 계성초, gyeseong1882.es.kr).
 * host 는 NEIS HMPG_ADRES 일괄 추출값 그대로 (id 와 subdomain 다른 학교 다수:
 * banpo→seoulbanpo, seowon→seo-won, seoil→seoulseoil).
 * id 는 모두 `seoul_` prefix — 다른 시도 학교와 명확히 구분 + 충돌 회피.
 */

import type { SchoolConfig } from '../index';

export const SEOCHO_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_gyeseong: {
    id: 'seoul_gyeseong',
    name: '계성초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091368' },
    // 사립 — gyeseong1882.es.kr 의 PHP 게시판형 식단표 (Stage 14-1-2, 2026-05-02).
    // 다른 사립 추가 시 sajipSchoolScraper.ts 그대로 재사용 가능.
    scrape: {
      kind: 'sajip-bbs',
      host: 'www.gyeseong1882.es.kr',
      bbsCategory: 'special_food_plan',
    },
  },
  seoul_snueps: {
    id: 'seoul_snueps',
    name: '서울교육대학교부설초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091367' },
    scrape: { kind: 'sen-es', host: 'snueps.sen.es.kr' },
  },
  seoul_maeheon: {
    id: 'seoul_maeheon',
    name: '서울매헌초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091384' },
    scrape: { kind: 'sen-es', host: 'maeheon.sen.es.kr' },
  },
  seoul_banwon: {
    id: 'seoul_banwon',
    name: '서울반원초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091385' },
    scrape: { kind: 'sen-es', host: 'banwon.sen.es.kr' },
  },
  seoul_banpo: {
    id: 'seoul_banpo',
    name: '서울반포초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091386' },
    scrape: { kind: 'sen-es', host: 'seoulbanpo.sen.es.kr' },
  },
  seoul_bangbae: {
    id: 'seoul_bangbae',
    name: '서울방배초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091387' },
    scrape: { kind: 'sen-es', host: 'bangbae.sen.es.kr' },
  },
  seoul_bangil: {
    id: 'seoul_bangil',
    name: '서울방일초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091388' },
    scrape: { kind: 'sen-es', host: 'bangil.sen.es.kr' },
  },
  seoul_banghyun: {
    id: 'seoul_banghyun',
    name: '서울방현초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091389' },
    scrape: { kind: 'sen-es', host: 'banghyun.sen.es.kr' },
  },
  seoul_seorae: {
    id: 'seoul_seorae',
    name: '서울서래초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091392' },
    scrape: { kind: 'sen-es', host: 'seorae.sen.es.kr' },
  },
  seoul_seowon: {
    id: 'seoul_seowon',
    name: '서울서원초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091393' },
    scrape: { kind: 'sen-es', host: 'seo-won.sen.es.kr' },
  },
  seoul_seoi: {
    id: 'seoul_seoi',
    name: '서울서이초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091394' },
    scrape: { kind: 'sen-es', host: 'seoi.sen.es.kr' },
  },
  seoul_seoil: {
    id: 'seoul_seoil',
    name: '서울서일초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091395' },
    scrape: { kind: 'sen-es', host: 'seoulseoil.sen.es.kr' },
  },
  seoul_seocho: {
    id: 'seoul_seocho',
    name: '서울서초초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091396' },
    scrape: { kind: 'sen-es', host: 'seocho.sen.es.kr' },
  },
  seoul_sindong: {
    id: 'seoul_sindong',
    name: '서울신동초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091399' },
    scrape: { kind: 'sen-es', host: 'sindong.sen.es.kr' },
  },
  seoul_sinjung: {
    id: 'seoul_sinjung',
    name: '서울신중초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091400' },
    scrape: { kind: 'sen-es', host: 'sinjung.sen.es.kr' },
  },
  seoul_yangjae: {
    id: 'seoul_yangjae',
    name: '서울양재초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091402' },
    scrape: { kind: 'sen-es', host: 'yangjae.sen.es.kr' },
  },
  seoul_eonnam: {
    id: 'seoul_eonnam',
    name: '서울언남초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091404' },
    scrape: { kind: 'sen-es', host: 'eonnam.sen.es.kr' },
  },
  seoul_woomyeon: {
    id: 'seoul_woomyeon',
    name: '서울우면초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091419' },
    scrape: { kind: 'sen-es', host: 'woomyeon.sen.es.kr' },
  },
  seoul_woosol: {
    id: 'seoul_woosol',
    name: '서울우솔초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091460' },
    scrape: { kind: 'sen-es', host: 'woosol.sen.es.kr' },
  },
  seoul_wooam: {
    id: 'seoul_wooam',
    name: '서울우암초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091410' },
    scrape: { kind: 'sen-es', host: 'wooam.sen.es.kr' },
  },
  seoul_wonmyong: {
    id: 'seoul_wonmyong',
    name: '서울원명초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091411' },
    scrape: { kind: 'sen-es', host: 'wonmyong.sen.es.kr' },
  },
  seoul_wonchon: {
    id: 'seoul_wonchon',
    name: '서울원촌초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091412' },
    scrape: { kind: 'sen-es', host: 'wonchon.sen.es.kr' },
  },
  seoul_isu: {
    id: 'seoul_isu',
    name: '서울이수초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091413' },
    scrape: { kind: 'sen-es', host: 'isu.sen.es.kr' },
  },
  seoul_jamwon: {
    id: 'seoul_jamwon',
    name: '서울잠원초등학교',
    level: 'elementary',
    region: '서울 서초',
    neis: { atptCode: 'B10', schoolCode: '7091415' },
    scrape: { kind: 'sen-es', host: 'jamwon.sen.es.kr' },
  },
};
