/**
 * 서울 성동구 21교 — Stage 14-20 (2026-05-03), Phase D 네 번째 자치구.
 *
 * 20교 sen.es.kr + 1교 (한양초 사립) host hye.or.kr → scrape 생략.
 * id 충돌 회피 위해 동음 학교에 `_sd` suffix (kyongil_sd, dongmyung_sd).
 */

import type { SchoolConfig } from '../index';

export const SEONGDONG_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_kyungdong: {
    id: 'seoul_kyungdong',
    name: '서울경동초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134078' },
    scrape: { kind: 'sen-es', host: 'kyungdong.sen.es.kr' },
  },
  seoul_kyeongsu: {
    id: 'seoul_kyeongsu',
    name: '서울경수초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134079' },
    scrape: { kind: 'sen-es', host: 'ks.sen.es.kr' },
  },
  seoul_kyongil_sd: {
    id: 'seoul_kyongil_sd',
    name: '서울경일초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134080' },
    scrape: { kind: 'sen-es', host: 'kyongil.sen.es.kr' },
  },
  seoul_geumbuk: {
    id: 'seoul_geumbuk',
    name: '서울금북초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134086' },
    scrape: { kind: 'sen-es', host: 'gb.sen.es.kr' },
  },
  seoul_geumok: {
    id: 'seoul_geumok',
    name: '서울금옥초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134087' },
    scrape: { kind: 'sen-es', host: 'geumok.sen.es.kr' },
  },
  seoul_geumho: {
    id: 'seoul_geumho',
    name: '서울금호초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134088' },
    scrape: { kind: 'sen-es', host: 'geumho.sen.es.kr' },
  },
  seoul_dongmyung_sd: {
    id: 'seoul_dongmyung_sd',
    name: '서울동명초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134089' },
    scrape: { kind: 'sen-es', host: 'dgmg.sen.es.kr' },
  },
  seoul_dongho: {
    id: 'seoul_dongho',
    name: '서울동호초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134092' },
    scrape: { kind: 'sen-es', host: 'dongho.sen.es.kr' },
  },
  seoul_majang: {
    id: 'seoul_majang',
    name: '서울마장초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134093' },
    scrape: { kind: 'sen-es', host: 'majang.sen.es.kr' },
  },
  seoul_muhag: {
    id: 'seoul_muhag',
    name: '서울무학초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134094' },
    scrape: { kind: 'sen-es', host: 'muhag.sen.es.kr' },
  },
  seoul_sageun: {
    id: 'seoul_sageun',
    name: '서울사근초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134095' },
    scrape: { kind: 'sen-es', host: 'sageun.sen.es.kr' },
  },
  seoul_sungsu: {
    id: 'seoul_sungsu',
    name: '서울성수초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134096' },
    scrape: { kind: 'sen-es', host: 'sungsu.sen.es.kr' },
  },
  seoul_songwon: {
    id: 'seoul_songwon',
    name: '서울송원초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134098' },
    scrape: { kind: 'sen-es', host: 'ssw.sen.es.kr' },
  },
  seoul_soongshin: {
    id: 'seoul_soongshin',
    name: '서울숭신초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134150' },
    scrape: { kind: 'sen-es', host: 'soongshin.sen.es.kr' },
  },
  seoul_oksu: {
    id: 'seoul_oksu',
    name: '서울옥수초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134103' },
    scrape: { kind: 'sen-es', host: 'oksu.sen.es.kr' },
  },
  seoul_okjeong: {
    id: 'seoul_okjeong',
    name: '서울옥정초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134104' },
    scrape: { kind: 'sen-es', host: 'okjeong.sen.es.kr' },
  },
  seoul_yongdab: {
    id: 'seoul_yongdab',
    name: '서울용답초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134106' },
    scrape: { kind: 'sen-es', host: 'yd.sen.es.kr' },
  },
  seoul_eungbong: {
    id: 'seoul_eungbong',
    name: '서울응봉초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134108' },
    scrape: { kind: 'sen-es', host: 'eb.sen.es.kr' },
  },
  seoul_haengdang: {
    id: 'seoul_haengdang',
    name: '서울행당초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134113' },
    scrape: { kind: 'sen-es', host: 'hd.sen.es.kr' },
  },
  seoul_haenghyun: {
    id: 'seoul_haenghyun',
    name: '서울행현초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134114' },
    scrape: { kind: 'sen-es', host: 'haenghyun.sen.es.kr' },
  },
  hanyang_es: {
    id: 'hanyang_es',
    name: '한양초등학교',
    level: 'elementary',
    region: '서울 성동',
    neis: { atptCode: 'B10', schoolCode: '7134118' },
    // scrape 생략 — host = www.hye.or.kr (사립). NEIS 메뉴만.
  },
};
