/**
 * 서울 성북구 29교 — Stage 14-24 (2026-05-03), Phase E 세 번째 자치구.
 *
 * 모두 sen.es.kr (사립 광운·대광·매원·성신·우촌 포함). id 충돌 없음.
 * 동신/월곡/장월은 동음 학교 있어 `_sb` suffix.
 */

import type { SchoolConfig } from '../index';

export const SEONGBUK_SCHOOLS: Record<string, SchoolConfig> = {
  kwangwoon_es: {
    id: 'kwangwoon_es',
    name: '광운초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121335' },
    scrape: { kind: 'sen-es', host: 'kwangwoon.sen.es.kr' },
  },
  daegwang_es: {
    id: 'daegwang_es',
    name: '대광초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121336' },
    scrape: { kind: 'sen-es', host: 'daegwang.sen.es.kr' },
  },
  maewon_es: {
    id: 'maewon_es',
    name: '매원초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121337' },
    scrape: { kind: 'sen-es', host: 'maewon.sen.es.kr' },
  },
  seoul_gaewoon: {
    id: 'seoul_gaewoon',
    name: '서울개운초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121298' },
    scrape: { kind: 'sen-es', host: 'gaewoon.sen.es.kr' },
  },
  seoul_gilwon: {
    id: 'seoul_gilwon',
    name: '서울길원초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121299' },
    scrape: { kind: 'sen-es', host: 'gilwon.sen.es.kr' },
  },
  seoul_gireum: {
    id: 'seoul_gireum',
    name: '서울길음초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121300' },
    scrape: { kind: 'sen-es', host: 'gireum.sen.es.kr' },
  },
  seoul_donam: {
    id: 'seoul_donam',
    name: '서울돈암초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121301' },
    scrape: { kind: 'sen-es', host: 'donam.sen.es.kr' },
  },
  seoul_dongsin_sb: {
    id: 'seoul_dongsin_sb',
    name: '서울동신초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121302' },
    scrape: { kind: 'sen-es', host: 'dongsin.sen.es.kr' },
  },
  seoul_mia: {
    id: 'seoul_mia',
    name: '서울미아초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121303' },
    scrape: { kind: 'sen-es', host: 'mia.sen.es.kr' },
  },
  seoul_samsun: {
    id: 'seoul_samsun',
    name: '서울삼선초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121307' },
    scrape: { kind: 'sen-es', host: 'samsun.sen.es.kr' },
  },
  seoul_sukgye: {
    id: 'seoul_sukgye',
    name: '서울석계초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121309' },
    scrape: { kind: 'sen-es', host: 'sukgye.sen.es.kr' },
  },
  seoul_seokgwan: {
    id: 'seoul_seokgwan',
    name: '서울석관초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121310' },
    scrape: { kind: 'sen-es', host: 'seokgwan.sen.es.kr' },
  },
  seoul_sungbuk: {
    id: 'seoul_sungbuk',
    name: '서울성북초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121311' },
    scrape: { kind: 'sen-es', host: 'sungbuk.sen.es.kr' },
  },
  seoul_soonggok: {
    id: 'seoul_soonggok',
    name: '서울숭곡초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121316' },
    scrape: { kind: 'sen-es', host: 'soonggok.sen.es.kr' },
  },
  seoul_soongduck: {
    id: 'seoul_soongduck',
    name: '서울숭덕초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121317' },
    scrape: { kind: 'sen-es', host: 'soongduck.sen.es.kr' },
  },
  seoul_sungrye: {
    id: 'seoul_sungrye',
    name: '서울숭례초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121318' },
    scrape: { kind: 'sen-es', host: 'sungrye.sen.es.kr' },
  },
  seoul_soongin: {
    id: 'seoul_soongin',
    name: '서울숭인초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121319' },
    scrape: { kind: 'sen-es', host: 'soongin.sen.es.kr' },
  },
  seoul_anam: {
    id: 'seoul_anam',
    name: '서울안암초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121320' },
    scrape: { kind: 'sen-es', host: 'anam.sen.es.kr' },
  },
  seoul_wolgok_sb: {
    id: 'seoul_wolgok_sb',
    name: '서울월곡초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121323' },
    scrape: { kind: 'sen-es', host: 'swg.sen.es.kr' },
  },
  seoul_ilshin: {
    id: 'seoul_ilshin',
    name: '서울일신초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121326' },
    scrape: { kind: 'sen-es', host: 'ilshin.sen.es.kr' },
  },
  seoul_janggok: {
    id: 'seoul_janggok',
    name: '서울장곡초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121327' },
    scrape: { kind: 'sen-es', host: 'janggok.sen.es.kr' },
  },
  seoul_jangwol_sb: {
    id: 'seoul_jangwol_sb',
    name: '서울장월초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121328' },
    scrape: { kind: 'sen-es', host: 'jangwol.sen.es.kr' },
  },
  seoul_jangwi: {
    id: 'seoul_jangwi',
    name: '서울장위초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121329' },
    scrape: { kind: 'sen-es', host: 'jangwicho.sen.es.kr' },
  },
  seoul_jeongdeok: {
    id: 'seoul_jeongdeok',
    name: '서울정덕초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121330' },
    scrape: { kind: 'sen-es', host: 'jeongdeok.sen.es.kr' },
  },
  seoul_jeongneung: {
    id: 'seoul_jeongneung',
    name: '서울정릉초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121331' },
    scrape: { kind: 'sen-es', host: 'jeongneung.sen.es.kr' },
  },
  seoul_jungsu: {
    id: 'seoul_jungsu',
    name: '서울정수초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121332' },
    scrape: { kind: 'sen-es', host: 'jungsu.sen.es.kr' },
  },
  seoul_cheongdeok: {
    id: 'seoul_cheongdeok',
    name: '서울청덕초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121333' },
    scrape: { kind: 'sen-es', host: 'cheongdeok.sen.es.kr' },
  },
  sungshin_es: {
    id: 'sungshin_es',
    name: '성신초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121338' },
    scrape: { kind: 'sen-es', host: 'sungshin.sen.es.kr' },
  },
  uchon_es: {
    id: 'uchon_es',
    name: '우촌초등학교',
    level: 'elementary',
    region: '서울 성북',
    neis: { atptCode: 'B10', schoolCode: '7121340' },
    scrape: { kind: 'sen-es', host: 'uchon.sen.es.kr' },
  },
};
