/**
 * 서울 송파구 41교 — Stage 14-5 (2026-05-02), Phase A 네 번째 자치구.
 *
 * 모두 sen.es.kr 패턴. 사립 0교. id 충돌 없음.
 * id 와 subdomain 다른 케이스 다수 (s-namcheon, smacheon, s-mh, sbangsan,
 * seoulbeodle, sree, ssj, sh, stosung 등 — `s-` 또는 `s` prefix strip).
 */

import type { SchoolConfig } from '../index';

export const SONGPA_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_gadong: {
    id: 'seoul_gadong',
    name: '서울가동초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130101' },
    scrape: { kind: 'sen-es', host: 'gadong.sen.es.kr' },
  },
  seoul_garak: {
    id: 'seoul_garak',
    name: '서울가락초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130102' },
    scrape: { kind: 'sen-es', host: 'garak.sen.es.kr' },
  },
  seoul_gawon: {
    id: 'seoul_gawon',
    name: '서울가원초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130103' },
    scrape: { kind: 'sen-es', host: 'gawon.sen.es.kr' },
  },
  seoul_gaju: {
    id: 'seoul_gaju',
    name: '서울가주초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130104' },
    scrape: { kind: 'sen-es', host: 'gaju.sen.es.kr' },
  },
  seoul_gaerong: {
    id: 'seoul_gaerong',
    name: '서울개롱초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130109' },
    scrape: { kind: 'sen-es', host: 'gaerong.sen.es.kr' },
  },
  seoul_geoyeo: {
    id: 'seoul_geoyeo',
    name: '서울거여초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130110' },
    scrape: { kind: 'sen-es', host: 'geo-yeo.sen.es.kr' },
  },
  seoul_geowon: {
    id: 'seoul_geowon',
    name: '서울거원초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130111' },
    scrape: { kind: 'sen-es', host: 'guhwon.sen.es.kr' },
  },
  seoul_namcheon: {
    id: 'seoul_namcheon',
    name: '서울남천초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130116' },
    scrape: { kind: 'sen-es', host: 's-namcheon.sen.es.kr' },
  },
  seoul_macheon: {
    id: 'seoul_macheon',
    name: '서울마천초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130119' },
    scrape: { kind: 'sen-es', host: 'smacheon.sen.es.kr' },
  },
  seoul_moondeok: {
    id: 'seoul_moondeok',
    name: '서울문덕초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130124' },
    scrape: { kind: 'sen-es', host: 'moondeok.sen.es.kr' },
  },
  seoul_moonjung: {
    id: 'seoul_moonjung',
    name: '서울문정초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130125' },
    scrape: { kind: 'sen-es', host: 'moonjung.sen.es.kr' },
  },
  seoul_moonhyeon: {
    id: 'seoul_moonhyeon',
    name: '서울문현초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130126' },
    scrape: { kind: 'sen-es', host: 's-mh.sen.es.kr' },
  },
  seoul_bangsan: {
    id: 'seoul_bangsan',
    name: '서울방산초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130127' },
    scrape: { kind: 'sen-es', host: 'sbangsan.sen.es.kr' },
  },
  seoul_bangi: {
    id: 'seoul_bangi',
    name: '서울방이초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130128' },
    scrape: { kind: 'sen-es', host: 'bangi.sen.es.kr' },
  },
  seoul_beodle: {
    id: 'seoul_beodle',
    name: '서울버들초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130129' },
    scrape: { kind: 'sen-es', host: 'seoulbeodle.sen.es.kr' },
  },
  seoul_samjeon: {
    id: 'seoul_samjeon',
    name: '서울삼전초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130130' },
    scrape: { kind: 'sen-es', host: 'samjeon.sen.es.kr' },
  },
  seoul_seokchon: {
    id: 'seoul_seokchon',
    name: '서울석촌초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130132' },
    scrape: { kind: 'sen-es', host: 'seokchon.sen.es.kr' },
  },
  seoul_seryun: {
    id: 'seoul_seryun',
    name: '서울세륜초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130137' },
    scrape: { kind: 'sen-es', host: 'seryun.sen.es.kr' },
  },
  seoul_songrye: {
    id: 'seoul_songrye',
    name: '서울송례초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130138' },
    scrape: { kind: 'sen-es', host: 'sree.sen.es.kr' },
  },
  seoul_songjeon: {
    id: 'seoul_songjeon',
    name: '서울송전초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130139' },
    scrape: { kind: 'sen-es', host: 'ssj.sen.es.kr' },
  },
  seoul_songpa: {
    id: 'seoul_songpa',
    name: '서울송파초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130140' },
    scrape: { kind: 'sen-es', host: 'songpa.sen.es.kr' },
  },
  seoul_singa: {
    id: 'seoul_singa',
    name: '서울신가초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130141' },
    scrape: { kind: 'sen-es', host: 'singa.sen.es.kr' },
  },
  seoul_sincheon: {
    id: 'seoul_sincheon',
    name: '서울신천초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130144' },
    scrape: { kind: 'sen-es', host: 'sh.sen.es.kr' },
  },
  seoul_aju: {
    id: 'seoul_aju',
    name: '서울아주초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130145' },
    scrape: { kind: 'sen-es', host: 'aju.sen.es.kr' },
  },
  seoul_youngpung: {
    id: 'seoul_youngpung',
    name: '서울영풍초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130146' },
    scrape: { kind: 'sen-es', host: 'youngpung.sen.es.kr' },
  },
  seoul_ogum: {
    id: 'seoul_ogum',
    name: '서울오금초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130147' },
    scrape: { kind: 'sen-es', host: 'ogum.sen.es.kr' },
  },
  seoul_oryun: {
    id: 'seoul_oryun',
    name: '서울오륜초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130148' },
    scrape: { kind: 'sen-es', host: 'oryun.sen.es.kr' },
  },
  seoul_westar: {
    id: 'seoul_westar',
    name: '서울위례별초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130245' },
    scrape: { kind: 'sen-es', host: 'westar.sen.es.kr' },
  },
  seoul_wiryesol: {
    id: 'seoul_wiryesol',
    name: '서울위례솔초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130270' },
    scrape: { kind: 'sen-es', host: 'wiryesol.sen.es.kr' },
  },
  seoul_jamdong: {
    id: 'seoul_jamdong',
    name: '서울잠동초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130150' },
    scrape: { kind: 'sen-es', host: 'jamdong.sen.es.kr' },
  },
  seoul_jamshin: {
    id: 'seoul_jamshin',
    name: '서울잠신초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130151' },
    scrape: { kind: 'sen-es', host: 'jamshin.sen.es.kr' },
  },
  seoul_jamsil: {
    id: 'seoul_jamsil',
    name: '서울잠실초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130152' },
    scrape: { kind: 'sen-es', host: 'jamsil.sen.es.kr' },
  },
  seoul_jamil: {
    id: 'seoul_jamil',
    name: '서울잠일초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130153' },
    scrape: { kind: 'sen-es', host: 'jamil.sen.es.kr' },
  },
  seoul_jamjeon: {
    id: 'seoul_jamjeon',
    name: '서울잠전초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130154' },
    scrape: { kind: 'sen-es', host: 'jamjeon.sen.es.kr' },
  },
  seoul_jamhyun: {
    id: 'seoul_jamhyun',
    name: '서울잠현초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130155' },
    scrape: { kind: 'sen-es', host: 'jamhyun.sen.es.kr' },
  },
  seoul_joongdae: {
    id: 'seoul_joongdae',
    name: '서울중대초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130156' },
    scrape: { kind: 'sen-es', host: 'joongdae.sen.es.kr' },
  },
  seoul_tosung: {
    id: 'seoul_tosung',
    name: '서울토성초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130160' },
    scrape: { kind: 'sen-es', host: 'stosung.sen.es.kr' },
  },
  seoul_pyunghwa: {
    id: 'seoul_pyunghwa',
    name: '서울평화초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130161' },
    scrape: { kind: 'sen-es', host: 'pyunghwa.sen.es.kr' },
  },
  seoul_poongnap: {
    id: 'seoul_poongnap',
    name: '서울풍납초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130162' },
    scrape: { kind: 'sen-es', host: 'poongnap.sen.es.kr' },
  },
  seoul_poongsung: {
    id: 'seoul_poongsung',
    name: '서울풍성초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130163' },
    scrape: { kind: 'sen-es', host: 'poongsung.sen.es.kr' },
  },
  seoul_haenuri: {
    id: 'seoul_haenuri',
    name: '서울해누리초등학교',
    level: 'elementary',
    region: '서울 송파',
    neis: { atptCode: 'B10', schoolCode: '7130255' },
    scrape: { kind: 'sen-es', host: 'haenuri.sen.es.kr' },
  },
};
