/**
 * 서울 양천구 30교 — Stage 14-10 (2026-05-02), Phase B 세 번째 자치구.
 *
 * 모두 sen.es.kr 패턴. id 충돌 없음.
 * host 약칭 (smd, sj, se, swc 등 다수).
 */

import type { SchoolConfig } from '../index';

export const YANGCHEON_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_galsan: {
    id: 'seoul_galsan',
    name: '서울갈산초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081420' },
    scrape: { kind: 'sen-es', host: 'galsan.sen.es.kr' },
  },
  seoul_gangseo: {
    id: 'seoul_gangseo',
    name: '서울강서초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081421' },
    scrape: { kind: 'sen-es', host: 'gangseo.sen.es.kr' },
  },
  seoul_kangsin: {
    id: 'seoul_kangsin',
    name: '서울강신초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081422' },
    scrape: { kind: 'sen-es', host: 'kangsin.sen.es.kr' },
  },
  seoul_gangwol: {
    id: 'seoul_gangwol',
    name: '서울강월초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081423' },
    scrape: { kind: 'sen-es', host: 'gangwol.sen.es.kr' },
  },
  seoul_kyongin: {
    id: 'seoul_kyongin',
    name: '서울경인초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081425' },
    scrape: { kind: 'sen-es', host: 'kyongin.sen.es.kr' },
  },
  seoul_gyenam: {
    id: 'seoul_gyenam',
    name: '서울계남초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081426' },
    scrape: { kind: 'sen-es', host: 'gyenam.sen.es.kr' },
  },
  seoul_nammyeong: {
    id: 'seoul_nammyeong',
    name: '서울남명초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081429' },
    scrape: { kind: 'sen-es', host: 'nammyeong.sen.es.kr' },
  },
  seoul_mokdong: {
    id: 'seoul_mokdong',
    name: '서울목동초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081438' },
    scrape: { kind: 'sen-es', host: 'smd.sen.es.kr' },
  },
  seoul_mogun: {
    id: 'seoul_mogun',
    name: '서울목운초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081439' },
    scrape: { kind: 'sen-es', host: 'mogun.sen.es.kr' },
  },
  seoul_mokwon: {
    id: 'seoul_mokwon',
    name: '서울목원초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081440' },
    scrape: { kind: 'sen-es', host: 'mokwon.sen.es.kr' },
  },
  seoul_seojeong: {
    id: 'seoul_seojeong',
    name: '서울서정초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081445' },
    scrape: { kind: 'sen-es', host: 'sj.sen.es.kr' },
  },
  seoul_singang: {
    id: 'seoul_singang',
    name: '서울신강초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081449' },
    scrape: { kind: 'sen-es', host: 'singang.sen.es.kr' },
  },
  seoul_singi: {
    id: 'seoul_singi',
    name: '서울신기초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081451' },
    scrape: { kind: 'sen-es', host: 'singi.sen.es.kr' },
  },
  seoul_sinnam: {
    id: 'seoul_sinnam',
    name: '서울신남초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081452' },
    scrape: { kind: 'sen-es', host: 'sinnam.sen.es.kr' },
  },
  seoul_sinmoc: {
    id: 'seoul_sinmoc',
    name: '서울신목초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081453' },
    scrape: { kind: 'sen-es', host: 'sinmoc.sen.es.kr' },
  },
  seoul_sinseo: {
    id: 'seoul_sinseo',
    name: '서울신서초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081454' },
    scrape: { kind: 'sen-es', host: 'sinseo.sen.es.kr' },
  },
  seoul_shinwon: {
    id: 'seoul_shinwon',
    name: '서울신원초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081455' },
    scrape: { kind: 'sen-es', host: 'shinwon.sen.es.kr' },
  },
  seoul_sineun: {
    id: 'seoul_sineun',
    name: '서울신은초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081482' },
    scrape: { kind: 'sen-es', host: 'se.sen.es.kr' },
  },
  seoul_yanggang: {
    id: 'seoul_yanggang',
    name: '서울양강초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081458' },
    scrape: { kind: 'sen-es', host: 'yanggang.sen.es.kr' },
  },
  seoul_yangdong: {
    id: 'seoul_yangdong',
    name: '서울양동초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081459' },
    scrape: { kind: 'sen-es', host: 'yangdong.sen.es.kr' },
  },
  seoul_yangmyung: {
    id: 'seoul_yangmyung',
    name: '서울양명초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081460' },
    scrape: { kind: 'sen-es', host: 'yangmyung.sen.es.kr' },
  },
  seoul_yangmok: {
    id: 'seoul_yangmok',
    name: '서울양목초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081461' },
    scrape: { kind: 'sen-es', host: 'yangmok.sen.es.kr' },
  },
  seoul_yangwon: {
    id: 'seoul_yangwon',
    name: '서울양원초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081462' },
    scrape: { kind: 'sen-es', host: 'yangwon.sen.es.kr' },
  },
  seoul_yanghwa: {
    id: 'seoul_yanghwa',
    name: '서울양화초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081464' },
    scrape: { kind: 'sen-es', host: 'yanghwa.sen.es.kr' },
  },
  seoul_youngdo: {
    id: 'seoul_youngdo',
    name: '서울영도초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081469' },
    scrape: { kind: 'sen-es', host: 'youngdo.sen.es.kr' },
  },
  seoul_wolchon: {
    id: 'seoul_wolchon',
    name: '서울월촌초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081472' },
    scrape: { kind: 'sen-es', host: 'swc.sen.es.kr' },
  },
  seoul_eunjung: {
    id: 'seoul_eunjung',
    name: '서울은정초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081473' },
    scrape: { kind: 'sen-es', host: 'eunjung.sen.es.kr' },
  },
  seoul_jangsoo: {
    id: 'seoul_jangsoo',
    name: '서울장수초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081474' },
    scrape: { kind: 'sen-es', host: 'jangsoo.sen.es.kr' },
  },
  seoul_jeongmok: {
    id: 'seoul_jeongmok',
    name: '서울정목초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081476' },
    scrape: { kind: 'sen-es', host: 'jeongmok.sen.es.kr' },
  },
  seoul_jihyang: {
    id: 'seoul_jihyang',
    name: '서울지향초등학교',
    level: 'elementary',
    region: '서울 양천',
    neis: { atptCode: 'B10', schoolCode: '7081477' },
    scrape: { kind: 'sen-es', host: 'jihyang.sen.es.kr' },
  },
};
