/**
 * 서울 영등포구 23교 — Stage 14-8 (2026-05-02), Phase B 첫 자치구.
 *
 * 모두 sen.es.kr 패턴. id 충돌 없음.
 * id 와 subdomain 다른 케이스 (idaegil, sdr, syw, ydp 등 약칭/접두사).
 */

import type { SchoolConfig } from '../index';

export const YEONGDEUNGPO_SCHOOLS: Record<string, SchoolConfig> = {
  seoul_dangsan: {
    id: 'seoul_dangsan',
    name: '서울당산초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041113' },
    scrape: { kind: 'sen-es', host: 'dangsan.sen.es.kr' },
  },
  seoul_dangseo: {
    id: 'seoul_dangseo',
    name: '서울당서초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041114' },
    scrape: { kind: 'sen-es', host: 'dangseo.sen.es.kr' },
  },
  seoul_dangjung: {
    id: 'seoul_dangjung',
    name: '서울당중초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041115' },
    scrape: { kind: 'sen-es', host: 'dangjung.sen.es.kr' },
  },
  seoul_daegil: {
    id: 'seoul_daegil',
    name: '서울대길초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041116' },
    scrape: { kind: 'sen-es', host: 'idaegil.sen.es.kr' },
  },
  seoul_daedong: {
    id: 'seoul_daedong',
    name: '서울대동초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041117' },
    scrape: { kind: 'sen-es', host: 'daedong.sen.es.kr' },
  },
  seoul_daebang: {
    id: 'seoul_daebang',
    name: '서울대방초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041118' },
    scrape: { kind: 'sen-es', host: 'daebang.sen.es.kr' },
  },
  seoul_daeyoung: {
    id: 'seoul_daeyoung',
    name: '서울대영초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041119' },
    scrape: { kind: 'sen-es', host: 'daeyoung.sen.es.kr' },
  },
  seoul_dorim: {
    id: 'seoul_dorim',
    name: '서울도림초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041121' },
    scrape: { kind: 'sen-es', host: 'seouldorim.sen.es.kr' },
  },
  seoul_doshin: {
    id: 'seoul_doshin',
    name: '서울도신초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041122' },
    scrape: { kind: 'sen-es', host: 'doshin.sen.es.kr' },
  },
  seoul_mullae: {
    id: 'seoul_mullae',
    name: '서울문래초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041128' },
    scrape: { kind: 'sen-es', host: 'mullae.sen.es.kr' },
  },
  seoul_seonyu: {
    id: 'seoul_seonyu',
    name: '서울선유초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041133' },
    scrape: { kind: 'sen-es', host: 'seonyu.sen.es.kr' },
  },
  seoul_sindaerim: {
    id: 'seoul_sindaerim',
    name: '서울신대림초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041137' },
    scrape: { kind: 'sen-es', host: 'sdr.sen.es.kr' },
  },
  seoul_shinyoung: {
    id: 'seoul_shinyoung',
    name: '서울신영초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041140' },
    scrape: { kind: 'sen-es', host: 'shinyoung.sen.es.kr' },
  },
  seoul_yeouido: {
    id: 'seoul_yeouido',
    name: '서울여의도초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041143' },
    scrape: { kind: 'sen-es', host: 'yeouido.sen.es.kr' },
  },
  seoul_youngdong: {
    id: 'seoul_youngdong',
    name: '서울영동초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041145' },
    scrape: { kind: 'sen-es', host: 'youngdong.sen.es.kr' },
  },
  seoul_yeongdeungpo: {
    id: 'seoul_yeongdeungpo',
    name: '서울영등포초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041146' },
    scrape: { kind: 'sen-es', host: 'ydp.sen.es.kr' },
  },
  seoul_younglim: {
    id: 'seoul_younglim',
    name: '서울영림초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041147' },
    scrape: { kind: 'sen-es', host: 'younglim.sen.es.kr' },
  },
  seoul_youngmoon: {
    id: 'seoul_youngmoon',
    name: '서울영문초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041148' },
    scrape: { kind: 'sen-es', host: 'youngmoon.sen.es.kr' },
  },
  seoul_youngsin: {
    id: 'seoul_youngsin',
    name: '서울영신초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041150' },
    scrape: { kind: 'sen-es', host: 'youngsin.sen.es.kr' },
  },
  seoul_youngwon: {
    id: 'seoul_youngwon',
    name: '서울영원초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041151' },
    scrape: { kind: 'sen-es', host: 'syw.sen.es.kr' },
  },
  seoul_youngjoong: {
    id: 'seoul_youngjoong',
    name: '서울영중초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041153' },
    scrape: { kind: 'sen-es', host: 'youngjoong.sen.es.kr' },
  },
  seoul_usin: {
    id: 'seoul_usin',
    name: '서울우신초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041158' },
    scrape: { kind: 'sen-es', host: 'usin.sen.es.kr' },
  },
  seoul_yunjung: {
    id: 'seoul_yunjung',
    name: '서울윤중초등학교',
    level: 'elementary',
    region: '서울 영등포',
    neis: { atptCode: 'B10', schoolCode: '7041159' },
    scrape: { kind: 'sen-es', host: 'yunjung.sen.es.kr' },
  },
};
