/**
 * 경기 수원시 초등학교 102교 — Stage 15 (2026-09-02).
 * 권선 34 / 영통 30 / 장안 22 / 팔달 16. 정렬: 구 순서 권선→영통→장안→팔달,
 * 구 내부 학교명 가나다순 (V-5 육안 표본이 각 구 첫 entry 로 고정되도록).
 *
 * ⚠️ 같은 이름의 `gyeonggi.ts` 파일과 `gyeonggi/` 디렉터리가 나란히 있는 것은
 * 의도된 구조다 (옵션 A-1). tsc bundler 해석에서 `./gyeonggi` 는 파일이 우선한다.
 * **`gyeonggi/index.ts` 를 만들지 말 것** — 만들면 `./gyeonggi` 해석이 뒤집혀
 * 기존 75교 import 가 조용히 바뀔 수 있다.
 *
 * - 도메인: 101교 전원 `*-e.goesw.kr` (수원 단일 인프라 — goeay/goegu 에 이은
 *   세 번째 경기 도메인). `kind: 'goeay'` 파서가 그대로 동작함을 실측
 *   (gosaek-e, mi=1315, thead 7/중식행 td 7 파싱, 3개 주에서 2·3·5장 추출).
 * - id: `suwon_<host subdomain 에서 -e 제거>` 기본. sysId `*cho-e` 이중 절단
 *   케이스 0건 실측 (AC-2c). 약칭 host 13개는 학교명 발음(국어 로마자 표기법)
 *   기반 수동 확정 — 2026-09-02 사용자 육안 대조 승인:
 *     dsw→dongsuwon (동수원초)      swsg→singok (수원신곡초)
 *     swjc→jungchon (수원중촌초)    hgok→hwanggok (황곡초)
 *     omokk→omok (오목초)           cmschool→cheongmyeong (청명초)
 *     swkumgok→geumgok (수원금곡초) swgumho→geumho (수원금호초)
 *     swmaehwa→maehwa (수원매화초)  swsunil→seonil (수원선일초)
 *     swhwaseo→hwaseo (화서초)      swhwayang→hwayang (화양초)
 *     eui→iui (이의초)
 *   ('수원X초'는 suwon_ prefix 가 수원을 이미 나타내므로 X 만 로마자화)
 * - mi 추출 실패 2교 (율전초 yuljeon-e, 황곡초 hgok-e) 는 scrape 생략 — 메뉴만
 *   노출. 후속 보정 대상: docs/suwon-mi-failures.md (Open Question 2 → 이월 확정)
 */

import type { SchoolConfig } from '../index';

export const SUWON_SCHOOLS: Record<string, SchoolConfig> = {
  // ---- 권선구 (34교) ----
  suwon_gosaek: {
    id: 'suwon_gosaek',
    name: '고색초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541066' },
    scrape: { kind: 'goeay', host: 'gosaek-e.goesw.kr', sysId: 'gosaek-e', mi: '1315' },
  },
  suwon_gohyun: {
    id: 'suwon_gohyun',
    name: '고현초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541067' },
    scrape: { kind: 'goeay', host: 'gohyun-e.goesw.kr', sysId: 'gohyun-e', mi: '2166' },
  },
  suwon_gokban: {
    id: 'suwon_gokban',
    name: '곡반초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541068' },
    scrape: { kind: 'goeay', host: 'gokban-e.goesw.kr', sysId: 'gokban-e', mi: '2510' },
  },
  suwon_gokseon: {
    id: 'suwon_gokseon',
    name: '곡선초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541069' },
    scrape: { kind: 'goeay', host: 'gokseon-e.goesw.kr', sysId: 'gokseon-e', mi: '3171' },
  },
  suwon_gokjeong: {
    id: 'suwon_gokjeong',
    name: '곡정초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541339' },
    scrape: { kind: 'goeay', host: 'gokjeong-e.goesw.kr', sysId: 'gokjeong-e', mi: '3589' },
  },
  suwon_guun: {
    id: 'suwon_guun',
    name: '구운초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541070' },
    scrape: { kind: 'goeay', host: 'guun-e.goesw.kr', sysId: 'guun-e', mi: '7147' },
  },
  suwon_kwonsun: {
    id: 'suwon_kwonsun',
    name: '권선초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541071' },
    scrape: { kind: 'goeay', host: 'kwonsun-e.goesw.kr', sysId: 'kwonsun-e', mi: '9178' },
  },
  suwon_gyujang: {
    id: 'suwon_gyujang',
    name: '규장초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541465' },
    scrape: { kind: 'goeay', host: 'gyujang-e.goesw.kr', sysId: 'gyujang-e', mi: '8349' },
  },
  suwon_namsuwon: {
    id: 'suwon_namsuwon',
    name: '남수원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541072' },
    scrape: { kind: 'goeay', host: 'namsuwon-e.goesw.kr', sysId: 'namsuwon-e', mi: '11305' },
  },
  suwon_neungsil: {
    id: 'suwon_neungsil',
    name: '능실초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541341' },
    scrape: { kind: 'goeay', host: 'neungsil-e.goesw.kr', sysId: 'neungsil-e', mi: '1799' },
  },
  suwon_dangsu: {
    id: 'suwon_dangsu',
    name: '당수초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541074' },
    scrape: { kind: 'goeay', host: 'dangsu-e.goesw.kr', sysId: 'dangsu-e', mi: '2979' },
  },
  suwon_myeongdang: {
    id: 'suwon_myeongdang',
    name: '명당초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541136' },
    scrape: { kind: 'goeay', host: 'myeongdang-e.goesw.kr', sysId: 'myeongdang-e', mi: '11362' },
  },
  suwon_sangchon: {
    id: 'suwon_sangchon',
    name: '상촌초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541138' },
    scrape: { kind: 'goeay', host: 'sangchon-e.goesw.kr', sysId: 'sangchon-e', mi: '11413' },
  },
  suwon_seopyung: {
    id: 'suwon_seopyung',
    name: '서평초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541145' },
    scrape: { kind: 'goeay', host: 'seopyung-e.goesw.kr', sysId: 'seopyung-e', mi: '12178' },
  },
  suwon_seoho: {
    id: 'suwon_seoho',
    name: '서호초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541083' },
    scrape: { kind: 'goeay', host: 'seoho-e.goesw.kr', sysId: 'seoho-e', mi: '14015' },
  },
  suwon_seonhaeng: {
    id: 'suwon_seonhaeng',
    name: '선행초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541328' },
    scrape: { kind: 'goeay', host: 'seonhaeng-e.goesw.kr', sysId: 'seonhaeng-e', mi: '15450' },
  },
  suwon_segok: {
    id: 'suwon_segok',
    name: '세곡초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541084' },
    scrape: { kind: 'goeay', host: 'segok-e.goesw.kr', sysId: 'segok-e', mi: '16286' },
  },
  suwon_seryu: {
    id: 'suwon_seryu',
    name: '세류초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541085' },
    scrape: { kind: 'goeay', host: 'seryu-e.goesw.kr', sysId: 'seryu-e', mi: '18153' },
  },
  suwon_suwongaon: {
    id: 'suwon_suwongaon',
    name: '수원가온초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541357' },
    scrape: { kind: 'goeay', host: 'suwongaon-e.goesw.kr', sysId: 'suwongaon-e', mi: '3281' },
  },
  suwon_geumgok: {
    id: 'suwon_geumgok',
    name: '수원금곡초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541088' },
    scrape: { kind: 'goeay', host: 'swkumgok-e.goesw.kr', sysId: 'swkumgok-e', mi: '3555' },
  },
  suwon_geumho: {
    id: 'suwon_geumho',
    name: '수원금호초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541381' },
    scrape: { kind: 'goeay', host: 'swgumho-e.goesw.kr', sysId: 'swgumho-e', mi: '3860' },
  },
  suwon_seonil: {
    id: 'suwon_seonil',
    name: '수원선일초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541089' },
    scrape: { kind: 'goeay', host: 'swsunil-e.goesw.kr', sysId: 'swsunil-e', mi: '4808' },
  },
  suwon_singok: {
    id: 'suwon_singok',
    name: '수원신곡초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541091' },
    scrape: { kind: 'goeay', host: 'swsg-e.goesw.kr', sysId: 'swsg-e', mi: '5021' },
  },
  suwon_jungchon: {
    id: 'suwon_jungchon',
    name: '수원중촌초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541342' },
    scrape: { kind: 'goeay', host: 'swjc-e.goesw.kr', sysId: 'swjc-e', mi: '5343' },
  },
  suwon_anryoung: {
    id: 'suwon_anryoung',
    name: '안룡초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541097' },
    scrape: { kind: 'goeay', host: 'anryoung-e.goesw.kr', sysId: 'anryoung-e', mi: '6198' },
  },
  suwon_omok: {
    id: 'suwon_omok',
    name: '오목초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541104' },
    scrape: { kind: 'goeay', host: 'omokk-e.goesw.kr', sysId: 'omokk-e', mi: '12491' },
  },
  suwon_ohyeon: {
    id: 'suwon_ohyeon',
    name: '오현초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541146' },
    scrape: { kind: 'goeay', host: 'ohyeon-e.goesw.kr', sysId: 'ohyeon-e', mi: '12859' },
  },
  suwon_ilwol: {
    id: 'suwon_ilwol',
    name: '일월초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541142' },
    scrape: { kind: 'goeay', host: 'ilwol-e.goesw.kr', sysId: 'ilwol-e', mi: '14024' },
  },
  suwon_ipbuk: {
    id: 'suwon_ipbuk',
    name: '입북초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541061' },
    scrape: { kind: 'goeay', host: 'ipbuk-e.goesw.kr', sysId: 'ipbuk-e', mi: '13835' },
  },
  suwon_suwonchilbo: {
    id: 'suwon_suwonchilbo',
    name: '칠보초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541119' },
    scrape: { kind: 'goeay', host: 'suwonchilbo-e.goesw.kr', sysId: 'suwonchilbo-e', mi: '1491' },
  },
  suwon_tapdong: {
    id: 'suwon_tapdong',
    name: '탑동초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541143' },
    scrape: { kind: 'goeay', host: 'tapdong-e.goesw.kr', sysId: 'tapdong-e', mi: '2653' },
  },
  suwon_homaeshil: {
    id: 'suwon_homaeshil',
    name: '호매실초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541122' },
    scrape: { kind: 'goeay', host: 'homaeshil-e.goesw.kr', sysId: 'homaeshil-e', mi: '13283' },
  },
  suwon_hyojeong: {
    id: 'suwon_hyojeong',
    name: '효정초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541130' },
    scrape: { kind: 'goeay', host: 'hyojeong-e.goesw.kr', sysId: 'hyojeong-e', mi: '11621' },
  },
  suwon_hyotap: {
    id: 'suwon_hyotap',
    name: '효탑초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541060' },
    scrape: { kind: 'goeay', host: 'hyotap-e.goesw.kr', sysId: 'hyotap-e', mi: '11164' },
  },
  // ---- 영통구 (30교) ----
  suwon_gwanggyo: {
    id: 'suwon_gwanggyo',
    name: '광교초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541329' },
    scrape: { kind: 'goeay', host: 'gwanggyo-e.goesw.kr', sysId: 'gwanggyo-e', mi: '4756' },
  },
  suwon_gwanggyohosu: {
    id: 'suwon_gwanggyohosu',
    name: '광교호수초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541399' },
    scrape: { kind: 'goeay', host: 'gwanggyohosu-e.goesw.kr', sysId: 'gwanggyohosu-e', mi: '12607' },
  },
  suwon_geulbit: {
    id: 'suwon_geulbit',
    name: '글빛초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541453' },
    scrape: { kind: 'goeay', host: 'geulbit-e.goesw.kr', sysId: 'geulbit-e', mi: '9804' },
  },
  suwon_daeseon: {
    id: 'suwon_daeseon',
    name: '대선초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541062' },
    scrape: { kind: 'goeay', host: 'daeseon-e.goesw.kr', sysId: 'daeseon-e', mi: '3451' },
  },
  suwon_dongsuwon: {
    id: 'suwon_dongsuwon',
    name: '동수원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541075' },
    scrape: { kind: 'goeay', host: 'dsw-e.goesw.kr', sysId: 'dsw-e', mi: '4384' },
  },
  suwon_mangpo: {
    id: 'suwon_mangpo',
    name: '망포초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541401' },
    scrape: { kind: 'goeay', host: 'mangpo-e.goesw.kr', sysId: 'mangpo-e', mi: '4927' },
  },
  suwon_maewon: {
    id: 'suwon_maewon',
    name: '매원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541077' },
    scrape: { kind: 'goeay', host: 'maewon-e.goesw.kr', sysId: 'maewon-e', mi: '19360' },
  },
  suwon_maetan: {
    id: 'suwon_maetan',
    name: '매탄초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541078' },
    scrape: { kind: 'goeay', host: 'maetan-e.goesw.kr', sysId: 'maetan-e', mi: '8783' },
  },
  suwon_maehyun: {
    id: 'suwon_maehyun',
    name: '매현초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541079' },
    scrape: { kind: 'goeay', host: 'maehyun-e.goesw.kr', sysId: 'maehyun-e', mi: '10103' },
  },
  suwon_sannam: {
    id: 'suwon_sannam',
    name: '산남초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541080' },
    scrape: { kind: 'goeay', host: 'sannam-e.goesw.kr', sysId: 'sannam-e', mi: '13741' },
  },
  suwon_sanui: {
    id: 'suwon_sanui',
    name: '산의초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541081' },
    scrape: { kind: 'goeay', host: 'sanui-e.goesw.kr', sysId: 'sanui-e', mi: '14210' },
  },
  suwon_sohwa: {
    id: 'suwon_sohwa',
    name: '소화초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541132' },
    scrape: { kind: 'goeay', host: 'sohwa-e.goesw.kr', sysId: 'sohwa-e', mi: '18187' },
  },
  suwon_maehwa: {
    id: 'suwon_maehwa',
    name: '수원매화초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541064' },
    scrape: { kind: 'goeay', host: 'swmaehwa-e.goesw.kr', sysId: 'swmaehwa-e', mi: '4346' },
  },
  suwon_shinsung: {
    id: 'suwon_shinsung',
    name: '신성초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541094' },
    scrape: { kind: 'goeay', host: 'shinsung-e.goesw.kr', sysId: 'shinsung-e', mi: '9797' },
  },
  suwon_sinyoung: {
    id: 'suwon_sinyoung',
    name: '신영초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541095' },
    scrape: { kind: 'goeay', host: 'sinyoung-e.goesw.kr', sysId: 'sinyoung-e', mi: '10145' },
  },
  suwon_shinpoong: {
    id: 'suwon_shinpoong',
    name: '신풍초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541096' },
    scrape: { kind: 'goeay', host: 'shinpoong-e.goesw.kr', sysId: 'shinpoong-e', mi: '5802' },
  },
  suwon_youngduk: {
    id: 'suwon_youngduk',
    name: '영덕초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541099' },
    scrape: { kind: 'goeay', host: 'youngduk-e.goesw.kr', sysId: 'youngduk-e', mi: '7992' },
  },
  suwon_youngdong: {
    id: 'suwon_youngdong',
    name: '영동초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541100' },
    scrape: { kind: 'goeay', host: 'youngdong-e.goesw.kr', sysId: 'youngdong-e', mi: '8337' },
  },
  suwon_youngil: {
    id: 'suwon_youngil',
    name: '영일초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541101' },
    scrape: { kind: 'goeay', host: 'youngil-e.goesw.kr', sysId: 'youngil-e', mi: '11229' },
  },
  suwon_youngtong: {
    id: 'suwon_youngtong',
    name: '영통초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541102' },
    scrape: { kind: 'goeay', host: 'youngtong-e.goesw.kr', sysId: 'youngtong-e', mi: '10373' },
  },
  suwon_wonil: {
    id: 'suwon_wonil',
    name: '원일초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541141' },
    scrape: { kind: 'goeay', host: 'wonil-e.goesw.kr', sysId: 'wonil-e', mi: '15760' },
  },
  suwon_wonchon: {
    id: 'suwon_wonchon',
    name: '원천초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541106' },
    scrape: { kind: 'goeay', host: 'wonchon-e.goesw.kr', sysId: 'wonchon-e', mi: '15593' },
  },
  suwon_iui: {
    id: 'suwon_iui',
    name: '이의초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541330' },
    scrape: { kind: 'goeay', host: 'eui-e.goesw.kr', sysId: 'eui-e', mi: '14499' },
  },
  suwon_jamwon: {
    id: 'suwon_jamwon',
    name: '잠원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541110' },
    scrape: { kind: 'goeay', host: 'jamwon-e.goesw.kr', sysId: 'jamwon-e', mi: '13204' },
  },
  // 사립 (www.suwoncca.org) — goeay/sen-es/sajip-bbs 어느 스크래퍼에도 해당 없음.
  // 서울 명지초·구로 천이초와 동일하게 scrape 생략: 메뉴는 보이고 사진은 안 보인다.
  // id 'suwon_cca'는 학교 공식 도메인(suwoncca.org)에서 따옴 — sysId 가 없어 자동
  // 생성이 불가한 유일 학교라 수동 부여 (2026-09-02 사용자 확정).
  suwon_cca: {
    id: 'suwon_cca',
    name: '중앙기독초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541133' },
  },
  suwon_cheongmyeong: {
    id: 'suwon_cheongmyeong',
    name: '청명초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541118' },
    scrape: { kind: 'goeay', host: 'cmschool-e.goesw.kr', sysId: 'cmschool-e', mi: '16931' },
  },
  suwon_taejang: {
    id: 'suwon_taejang',
    name: '태장초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541120' },
    scrape: { kind: 'goeay', host: 'taejang-e.goesw.kr', sysId: 'taejang-e', mi: '5682' },
  },
  suwon_hwanggok: {
    id: 'suwon_hwanggok',
    name: '황곡초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541123' },
  },
  suwon_hyodong: {
    id: 'suwon_hyodong',
    name: '효동초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541127' },
    scrape: { kind: 'goeay', host: 'hyodong-e.goesw.kr', sysId: 'hyodong-e', mi: '12955' },
  },
  suwon_hyowon: {
    id: 'suwon_hyowon',
    name: '효원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541129' },
    scrape: { kind: 'goeay', host: 'hyowon-e.goesw.kr', sysId: 'hyowon-e', mi: '11904' },
  },
  // ---- 장안구 (22교) ----
  suwon_dasol: {
    id: 'suwon_dasol',
    name: '다솔초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541356' },
    scrape: { kind: 'goeay', host: 'dasol-e.goesw.kr', sysId: 'dasol-e', mi: '2067' },
  },
  suwon_daepyong: {
    id: 'suwon_daepyong',
    name: '대평초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541134' },
    scrape: { kind: 'goeay', host: 'daepyong-e.goesw.kr', sysId: 'daepyong-e', mi: '4026' },
  },
  suwon_myoungin: {
    id: 'suwon_myoungin',
    name: '명인초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541137' },
    scrape: { kind: 'goeay', host: 'myoungin-e.goesw.kr', sysId: 'myoungin-e', mi: '11821' },
  },
  suwon_sangryul: {
    id: 'suwon_sangryul',
    name: '상률초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541082' },
    scrape: { kind: 'goeay', host: 'sangryul-e.goesw.kr', sysId: 'sangryul-e', mi: '10888' },
  },
  suwon_songlim: {
    id: 'suwon_songlim',
    name: '송림초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541139' },
    scrape: { kind: 'goeay', host: 'songlim-e.goesw.kr', sysId: 'songlim-e', mi: '10389' },
  },
  suwon_songwon: {
    id: 'suwon_songwon',
    name: '송원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541140' },
    scrape: { kind: 'goeay', host: 'songwon-e.goesw.kr', sysId: 'songwon-e', mi: '1576' },
  },
  suwon_songjeong: {
    id: 'suwon_songjeong',
    name: '송정초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541086' },
    scrape: { kind: 'goeay', host: 'songjeong-e.goesw.kr', sysId: 'songjeong-e', mi: '2030' },
  },
  suwon_songjook: {
    id: 'suwon_songjook',
    name: '송죽초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541087' },
    scrape: { kind: 'goeay', host: 'songjook-e.goesw.kr', sysId: 'songjook-e', mi: '2345' },
  },
  suwon_sooseong: {
    id: 'suwon_sooseong',
    name: '수성초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541090' },
    scrape: { kind: 'goeay', host: 'sooseong-e.goesw.kr', sysId: 'sooseong-e', mi: '2699' },
  },
  suwon_suwondongsin: {
    id: 'suwon_suwondongsin',
    name: '수원동신초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541384' },
    scrape: { kind: 'goeay', host: 'suwondongsin-e.goesw.kr', sysId: 'suwondongsin-e', mi: '4072' },
  },
  suwon_suil: {
    id: 'suwon_suil',
    name: '수일초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541063' },
    scrape: { kind: 'goeay', host: 'suil-e.goesw.kr', sysId: 'suil-e', mi: '7867' },
  },
  suwon_younghwa: {
    id: 'suwon_younghwa',
    name: '영화초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541103' },
    scrape: { kind: 'goeay', host: 'younghwa-e.goesw.kr', sysId: 'younghwa-e', mi: '12082' },
  },
  suwon_yuljeon: {
    id: 'suwon_yuljeon',
    name: '율전초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541107' },
  },
  suwon_jungja: {
    id: 'suwon_jungja',
    name: '정자초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541111' },
    scrape: { kind: 'goeay', host: 'jungja-e.goesw.kr', sysId: 'jungja-e', mi: '13812' },
  },
  suwon_jungchun: {
    id: 'suwon_jungchun',
    name: '정천초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541112' },
    scrape: { kind: 'goeay', host: 'jungchun-e.goesw.kr', sysId: 'jungchun-e', mi: '14381' },
  },
  suwon_jowon: {
    id: 'suwon_jowon',
    name: '조원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541113' },
    scrape: { kind: 'goeay', host: 'jowon-e.goesw.kr', sysId: 'jowon-e', mi: '14694' },
  },
  suwon_changyong: {
    id: 'suwon_changyong',
    name: '창용초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541115' },
    scrape: { kind: 'goeay', host: 'changyong-e.goesw.kr', sysId: 'changyong-e', mi: '15597' },
  },
  suwon_cheonil: {
    id: 'suwon_cheonil',
    name: '천일초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541116' },
    scrape: { kind: 'goeay', host: 'cheonil-e.goesw.kr', sysId: 'cheonil-e', mi: '16118' },
  },
  suwon_cheon: {
    id: 'suwon_cheon',
    name: '천천초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541117' },
    scrape: { kind: 'goeay', host: 'cheon-e.goesw.kr', sysId: 'cheon-e', mi: '16527' },
  },
  suwon_pajang: {
    id: 'suwon_pajang',
    name: '파장초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541121' },
    scrape: { kind: 'goeay', host: 'pajang-e.goesw.kr', sysId: 'pajang-e', mi: '8950' },
  },
  suwon_hanil: {
    id: 'suwon_hanil',
    name: '한일초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541144' },
    scrape: { kind: 'goeay', host: 'hanil-e.goesw.kr', sysId: 'hanil-e', mi: '11747' },
  },
  suwon_hyochun: {
    id: 'suwon_hyochun',
    name: '효천초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541131' },
    scrape: { kind: 'goeay', host: 'hyochun-e.goesw.kr', sysId: 'hyochun-e', mi: '11480' },
  },
  // ---- 팔달구 (16교) ----
  suwon_namchang: {
    id: 'suwon_namchang',
    name: '남창초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541073' },
    scrape: { kind: 'goeay', host: 'namchang-e.goesw.kr', sysId: 'namchang-e', mi: '11771' },
  },
  suwon_maegyo: {
    id: 'suwon_maegyo',
    name: '매교초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541463' },
    scrape: { kind: 'goeay', host: 'maegyo-e.goesw.kr', sysId: 'maegyo-e', mi: '6012' },
  },
  suwon_maesan: {
    id: 'suwon_maesan',
    name: '매산초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541076' },
    scrape: { kind: 'goeay', host: 'maesan-e.goesw.kr', sysId: 'maesan-e', mi: '6872' },
  },
  suwon_maeyeoul: {
    id: 'suwon_maeyeoul',
    name: '매여울초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541235' },
    scrape: { kind: 'goeay', host: 'maeyeoul-e.goesw.kr', sysId: 'maeyeoul-e', mi: '7576' },
  },
  suwon_suwon: {
    id: 'suwon_suwon',
    name: '수원초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541092' },
    scrape: { kind: 'goeay', host: 'suwon-e.goesw.kr', sysId: 'suwon-e', mi: '6003' },
  },
  suwon_sukji: {
    id: 'suwon_sukji',
    name: '숙지초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541093' },
    scrape: { kind: 'goeay', host: 'sukji-e.goesw.kr', sysId: 'sukji-e', mi: '8392' },
  },
  suwon_yonmu: {
    id: 'suwon_yonmu',
    name: '연무초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541098' },
    scrape: { kind: 'goeay', host: 'yonmu-e.goesw.kr', sysId: 'yonmu-e', mi: '7354' },
  },
  suwon_wooman: {
    id: 'suwon_wooman',
    name: '우만초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541105' },
    scrape: { kind: 'goeay', host: 'wooman-e.goesw.kr', sysId: 'wooman-e', mi: '16014' },
  },
  suwon_youlhyun: {
    id: 'suwon_youlhyun',
    name: '율현초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541108' },
    scrape: { kind: 'goeay', host: 'youlhyun-e.goesw.kr', sysId: 'youlhyun-e', mi: '15200' },
  },
  suwon_ingyue: {
    id: 'suwon_ingyue',
    name: '인계초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541109' },
    scrape: { kind: 'goeay', host: 'ingyue-e.goesw.kr', sysId: 'ingyue-e', mi: '14267' },
  },
  suwon_jidong: {
    id: 'suwon_jidong',
    name: '지동초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541114' },
    scrape: { kind: 'goeay', host: 'jidong-e.goesw.kr', sysId: 'jidong-e', mi: '15191' },
  },
  suwon_paldal: {
    id: 'suwon_paldal',
    name: '팔달초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541065' },
    scrape: { kind: 'goeay', host: 'paldal-e.goesw.kr', sysId: 'paldal-e', mi: '9765' },
  },
  suwon_hwaseo: {
    id: 'suwon_hwaseo',
    name: '화서초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541124' },
    scrape: { kind: 'goeay', host: 'swhwaseo-e.goesw.kr', sysId: 'swhwaseo-e', mi: '13668' },
  },
  suwon_hwayang: {
    id: 'suwon_hwayang',
    name: '화양초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541125' },
    scrape: { kind: 'goeay', host: 'swhwayang-e.goesw.kr', sysId: 'swhwayang-e', mi: '14652' },
  },
  suwon_hwahong: {
    id: 'suwon_hwahong',
    name: '화홍초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541126' },
    scrape: { kind: 'goeay', host: 'hwahong-e.goesw.kr', sysId: 'hwahong-e', mi: '13477' },
  },
  suwon_hyoseong: {
    id: 'suwon_hyoseong',
    name: '효성초등학교',
    level: 'elementary',
    region: '경기 수원',
    neis: { atptCode: 'J10', schoolCode: '7541128' },
    scrape: { kind: 'goeay', host: 'hyoseong-e.goesw.kr', sysId: 'hyoseong-e', mi: '12414' },
  },
};
